// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.appbar.MaterialToolbar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiSwipeRefreshLayout;

public final class ActivityUserContribBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final WikiSwipeRefreshLayout refreshContainer;

  @NonNull
  public final MaterialToolbar toolbar;

  @NonNull
  public final CoordinatorLayout userContribCoordinator;

  @NonNull
  public final RecyclerView userContribRecycler;

  private ActivityUserContribBinding(@NonNull LinearLayout rootView,
      @NonNull WikiSwipeRefreshLayout refreshContainer, @NonNull MaterialToolbar toolbar,
      @NonNull CoordinatorLayout userContribCoordinator,
      @NonNull RecyclerView userContribRecycler) {
    this.rootView = rootView;
    this.refreshContainer = refreshContainer;
    this.toolbar = toolbar;
    this.userContribCoordinator = userContribCoordinator;
    this.userContribRecycler = userContribRecycler;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUserContribBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUserContribBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_user_contrib, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUserContribBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.refresh_container;
      WikiSwipeRefreshLayout refreshContainer = ViewBindings.findChildViewById(rootView, id);
      if (refreshContainer == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.user_contrib_coordinator;
      CoordinatorLayout userContribCoordinator = ViewBindings.findChildViewById(rootView, id);
      if (userContribCoordinator == null) {
        break missingId;
      }

      id = R.id.user_contrib_recycler;
      RecyclerView userContribRecycler = ViewBindings.findChildViewById(rootView, id);
      if (userContribRecycler == null) {
        break missingId;
      }

      return new ActivityUserContribBinding((LinearLayout) rootView, refreshContainer, toolbar,
          userContribCoordinator, userContribRecycler);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
