// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.progressindicator.LinearProgressIndicator;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiErrorView;

public final class ActivityLoginBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final GroupCaptchaBinding captchaContainer;

  @NonNull
  public final InflateLoginAndAccountCreationFooterBinding footerContainer;

  @NonNull
  public final TextInputLayout login2faText;

  @NonNull
  public final Button loginButton;

  @NonNull
  public final Button loginCreateAccountButton;

  @NonNull
  public final TextInputLayout loginPasswordInput;

  @NonNull
  public final LinearLayout loginPrimaryContainer;

  @NonNull
  public final TextInputLayout loginUsernameText;

  @NonNull
  public final WikiErrorView viewLoginError;

  @NonNull
  public final LinearProgressIndicator viewProgressBar;

  private ActivityLoginBinding(@NonNull FrameLayout rootView,
      @NonNull GroupCaptchaBinding captchaContainer,
      @NonNull InflateLoginAndAccountCreationFooterBinding footerContainer,
      @NonNull TextInputLayout login2faText, @NonNull Button loginButton,
      @NonNull Button loginCreateAccountButton, @NonNull TextInputLayout loginPasswordInput,
      @NonNull LinearLayout loginPrimaryContainer, @NonNull TextInputLayout loginUsernameText,
      @NonNull WikiErrorView viewLoginError, @NonNull LinearProgressIndicator viewProgressBar) {
    this.rootView = rootView;
    this.captchaContainer = captchaContainer;
    this.footerContainer = footerContainer;
    this.login2faText = login2faText;
    this.loginButton = loginButton;
    this.loginCreateAccountButton = loginCreateAccountButton;
    this.loginPasswordInput = loginPasswordInput;
    this.loginPrimaryContainer = loginPrimaryContainer;
    this.loginUsernameText = loginUsernameText;
    this.viewLoginError = viewLoginError;
    this.viewProgressBar = viewProgressBar;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.captcha_container;
      View captchaContainer = ViewBindings.findChildViewById(rootView, id);
      if (captchaContainer == null) {
        break missingId;
      }
      GroupCaptchaBinding binding_captchaContainer = GroupCaptchaBinding.bind(captchaContainer);

      id = R.id.footer_container;
      View footerContainer = ViewBindings.findChildViewById(rootView, id);
      if (footerContainer == null) {
        break missingId;
      }
      InflateLoginAndAccountCreationFooterBinding binding_footerContainer = InflateLoginAndAccountCreationFooterBinding.bind(footerContainer);

      id = R.id.login_2fa_text;
      TextInputLayout login2faText = ViewBindings.findChildViewById(rootView, id);
      if (login2faText == null) {
        break missingId;
      }

      id = R.id.login_button;
      Button loginButton = ViewBindings.findChildViewById(rootView, id);
      if (loginButton == null) {
        break missingId;
      }

      id = R.id.login_create_account_button;
      Button loginCreateAccountButton = ViewBindings.findChildViewById(rootView, id);
      if (loginCreateAccountButton == null) {
        break missingId;
      }

      id = R.id.login_password_input;
      TextInputLayout loginPasswordInput = ViewBindings.findChildViewById(rootView, id);
      if (loginPasswordInput == null) {
        break missingId;
      }

      id = R.id.login_primary_container;
      LinearLayout loginPrimaryContainer = ViewBindings.findChildViewById(rootView, id);
      if (loginPrimaryContainer == null) {
        break missingId;
      }

      id = R.id.login_username_text;
      TextInputLayout loginUsernameText = ViewBindings.findChildViewById(rootView, id);
      if (loginUsernameText == null) {
        break missingId;
      }

      id = R.id.view_login_error;
      WikiErrorView viewLoginError = ViewBindings.findChildViewById(rootView, id);
      if (viewLoginError == null) {
        break missingId;
      }

      id = R.id.view_progress_bar;
      LinearProgressIndicator viewProgressBar = ViewBindings.findChildViewById(rootView, id);
      if (viewProgressBar == null) {
        break missingId;
      }

      return new ActivityLoginBinding((FrameLayout) rootView, binding_captchaContainer,
          binding_footerContainer, login2faText, loginButton, loginCreateAccountButton,
          loginPasswordInput, loginPrimaryContainer, loginUsernameText, viewLoginError,
          viewProgressBar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
