// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.progressindicator.LinearProgressIndicator;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiErrorView;

public final class ActivityResetPasswordBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final TextInputLayout login2faText;

  @NonNull
  public final Button loginButton;

  @NonNull
  public final TextInputLayout resetPasswordInput;

  @NonNull
  public final TextInputLayout resetPasswordRepeat;

  @NonNull
  public final WikiErrorView viewLoginError;

  @NonNull
  public final LinearProgressIndicator viewProgressBar;

  private ActivityResetPasswordBinding(@NonNull FrameLayout rootView,
      @NonNull TextInputLayout login2faText, @NonNull Button loginButton,
      @NonNull TextInputLayout resetPasswordInput, @NonNull TextInputLayout resetPasswordRepeat,
      @NonNull WikiErrorView viewLoginError, @NonNull LinearProgressIndicator viewProgressBar) {
    this.rootView = rootView;
    this.login2faText = login2faText;
    this.loginButton = loginButton;
    this.resetPasswordInput = resetPasswordInput;
    this.resetPasswordRepeat = resetPasswordRepeat;
    this.viewLoginError = viewLoginError;
    this.viewProgressBar = viewProgressBar;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityResetPasswordBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityResetPasswordBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_reset_password, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityResetPasswordBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.login_2fa_text;
      TextInputLayout login2faText = ViewBindings.findChildViewById(rootView, id);
      if (login2faText == null) {
        break missingId;
      }

      id = R.id.login_button;
      Button loginButton = ViewBindings.findChildViewById(rootView, id);
      if (loginButton == null) {
        break missingId;
      }

      id = R.id.reset_password_input;
      TextInputLayout resetPasswordInput = ViewBindings.findChildViewById(rootView, id);
      if (resetPasswordInput == null) {
        break missingId;
      }

      id = R.id.reset_password_repeat;
      TextInputLayout resetPasswordRepeat = ViewBindings.findChildViewById(rootView, id);
      if (resetPasswordRepeat == null) {
        break missingId;
      }

      id = R.id.view_login_error;
      WikiErrorView viewLoginError = ViewBindings.findChildViewById(rootView, id);
      if (viewLoginError == null) {
        break missingId;
      }

      id = R.id.view_progress_bar;
      LinearProgressIndicator viewProgressBar = ViewBindings.findChildViewById(rootView, id);
      if (viewProgressBar == null) {
        break missingId;
      }

      return new ActivityResetPasswordBinding((FrameLayout) rootView, login2faText, loginButton,
          resetPasswordInput, resetPasswordRepeat, viewLoginError, viewProgressBar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
