// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.PlainPasteEditText;

public final class DialogTextInputBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final PlainPasteEditText secondaryTextInput;

  @NonNull
  public final TextInputLayout secondaryTextInputContainer;

  @NonNull
  public final PlainPasteEditText textInput;

  @NonNull
  public final TextInputLayout textInputContainer;

  private DialogTextInputBinding(@NonNull LinearLayout rootView,
      @NonNull PlainPasteEditText secondaryTextInput,
      @NonNull TextInputLayout secondaryTextInputContainer, @NonNull PlainPasteEditText textInput,
      @NonNull TextInputLayout textInputContainer) {
    this.rootView = rootView;
    this.secondaryTextInput = secondaryTextInput;
    this.secondaryTextInputContainer = secondaryTextInputContainer;
    this.textInput = textInput;
    this.textInputContainer = textInputContainer;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogTextInputBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogTextInputBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_text_input, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogTextInputBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.secondary_text_input;
      PlainPasteEditText secondaryTextInput = ViewBindings.findChildViewById(rootView, id);
      if (secondaryTextInput == null) {
        break missingId;
      }

      id = R.id.secondary_text_input_container;
      TextInputLayout secondaryTextInputContainer = ViewBindings.findChildViewById(rootView, id);
      if (secondaryTextInputContainer == null) {
        break missingId;
      }

      id = R.id.text_input;
      PlainPasteEditText textInput = ViewBindings.findChildViewById(rootView, id);
      if (textInput == null) {
        break missingId;
      }

      id = R.id.text_input_container;
      TextInputLayout textInputContainer = ViewBindings.findChildViewById(rootView, id);
      if (textInputContainer == null) {
        break missingId;
      }

      return new DialogTextInputBinding((LinearLayout) rootView, secondaryTextInput,
          secondaryTextInputContainer, textInput, textInputContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
