// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.PlainPasteEditText;

public final class DialogFeedbackInputBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final PlainPasteEditText feedbackInput;

  @NonNull
  public final TextInputLayout feedbackInputContainer;

  private DialogFeedbackInputBinding(@NonNull ScrollView rootView,
      @NonNull PlainPasteEditText feedbackInput, @NonNull TextInputLayout feedbackInputContainer) {
    this.rootView = rootView;
    this.feedbackInput = feedbackInput;
    this.feedbackInputContainer = feedbackInputContainer;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogFeedbackInputBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogFeedbackInputBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_feedback_input, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogFeedbackInputBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.feedbackInput;
      PlainPasteEditText feedbackInput = ViewBindings.findChildViewById(rootView, id);
      if (feedbackInput == null) {
        break missingId;
      }

      id = R.id.feedbackInputContainer;
      TextInputLayout feedbackInputContainer = ViewBindings.findChildViewById(rootView, id);
      if (feedbackInputContainer == null) {
        break missingId;
      }

      return new DialogFeedbackInputBinding((ScrollView) rootView, feedbackInput,
          feedbackInputContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
