// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class DialogInsertMediaTypeBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout imageTypeBasic;

  @NonNull
  public final LinearLayout imageTypeFrame;

  @NonNull
  public final LinearLayout imageTypeFrameless;

  @NonNull
  public final LinearLayout imageTypeThumbnail;

  private DialogInsertMediaTypeBinding(@NonNull LinearLayout rootView,
      @NonNull LinearLayout imageTypeBasic, @NonNull LinearLayout imageTypeFrame,
      @NonNull LinearLayout imageTypeFrameless, @NonNull LinearLayout imageTypeThumbnail) {
    this.rootView = rootView;
    this.imageTypeBasic = imageTypeBasic;
    this.imageTypeFrame = imageTypeFrame;
    this.imageTypeFrameless = imageTypeFrameless;
    this.imageTypeThumbnail = imageTypeThumbnail;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogInsertMediaTypeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogInsertMediaTypeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_insert_media_type, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogInsertMediaTypeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageTypeBasic;
      LinearLayout imageTypeBasic = ViewBindings.findChildViewById(rootView, id);
      if (imageTypeBasic == null) {
        break missingId;
      }

      id = R.id.imageTypeFrame;
      LinearLayout imageTypeFrame = ViewBindings.findChildViewById(rootView, id);
      if (imageTypeFrame == null) {
        break missingId;
      }

      id = R.id.imageTypeFrameless;
      LinearLayout imageTypeFrameless = ViewBindings.findChildViewById(rootView, id);
      if (imageTypeFrameless == null) {
        break missingId;
      }

      id = R.id.imageTypeThumbnail;
      LinearLayout imageTypeThumbnail = ViewBindings.findChildViewById(rootView, id);
      if (imageTypeThumbnail == null) {
        break missingId;
      }

      return new DialogInsertMediaTypeBinding((LinearLayout) rootView, imageTypeBasic,
          imageTypeFrame, imageTypeFrameless, imageTypeThumbnail);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
