// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatImageView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class DialogArticleDescriptionsBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final AppCompatImageView closeButton;

  @NonNull
  public final LinearLayout descriptionsContainer;

  @NonNull
  public final TextView firstSuggestion;

  @NonNull
  public final AppCompatImageView firstSuggestionFlag;

  @NonNull
  public final TextView secondSuggestion;

  @NonNull
  public final AppCompatImageView secondSuggestionFlag;

  @NonNull
  public final LinearLayout secondSuggestionLayout;

  private DialogArticleDescriptionsBinding(@NonNull ScrollView rootView,
      @NonNull AppCompatImageView closeButton, @NonNull LinearLayout descriptionsContainer,
      @NonNull TextView firstSuggestion, @NonNull AppCompatImageView firstSuggestionFlag,
      @NonNull TextView secondSuggestion, @NonNull AppCompatImageView secondSuggestionFlag,
      @NonNull LinearLayout secondSuggestionLayout) {
    this.rootView = rootView;
    this.closeButton = closeButton;
    this.descriptionsContainer = descriptionsContainer;
    this.firstSuggestion = firstSuggestion;
    this.firstSuggestionFlag = firstSuggestionFlag;
    this.secondSuggestion = secondSuggestion;
    this.secondSuggestionFlag = secondSuggestionFlag;
    this.secondSuggestionLayout = secondSuggestionLayout;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogArticleDescriptionsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogArticleDescriptionsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_article_descriptions, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogArticleDescriptionsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.closeButton;
      AppCompatImageView closeButton = ViewBindings.findChildViewById(rootView, id);
      if (closeButton == null) {
        break missingId;
      }

      id = R.id.descriptionsContainer;
      LinearLayout descriptionsContainer = ViewBindings.findChildViewById(rootView, id);
      if (descriptionsContainer == null) {
        break missingId;
      }

      id = R.id.firstSuggestion;
      TextView firstSuggestion = ViewBindings.findChildViewById(rootView, id);
      if (firstSuggestion == null) {
        break missingId;
      }

      id = R.id.firstSuggestionFlag;
      AppCompatImageView firstSuggestionFlag = ViewBindings.findChildViewById(rootView, id);
      if (firstSuggestionFlag == null) {
        break missingId;
      }

      id = R.id.secondSuggestion;
      TextView secondSuggestion = ViewBindings.findChildViewById(rootView, id);
      if (secondSuggestion == null) {
        break missingId;
      }

      id = R.id.secondSuggestionFlag;
      AppCompatImageView secondSuggestionFlag = ViewBindings.findChildViewById(rootView, id);
      if (secondSuggestionFlag == null) {
        break missingId;
      }

      id = R.id.secondSuggestionLayout;
      LinearLayout secondSuggestionLayout = ViewBindings.findChildViewById(rootView, id);
      if (secondSuggestionLayout == null) {
        break missingId;
      }

      return new DialogArticleDescriptionsBinding((ScrollView) rootView, closeButton,
          descriptionsContainer, firstSuggestion, firstSuggestionFlag, secondSuggestion,
          secondSuggestionFlag, secondSuggestionLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
