// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiErrorView;

public final class DialogCategoriesBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final TextView categoriesDialogPageTitle;

  @NonNull
  public final TextView categoriesDialogTitle;

  @NonNull
  public final WikiErrorView categoriesError;

  @NonNull
  public final TextView categoriesNoneFound;

  @NonNull
  public final RecyclerView categoriesRecycler;

  @NonNull
  public final ImageView categoriesThumbnail;

  @NonNull
  public final ProgressBar dialogCategoriesProgress;

  private DialogCategoriesBinding(@NonNull FrameLayout rootView,
      @NonNull TextView categoriesDialogPageTitle, @NonNull TextView categoriesDialogTitle,
      @NonNull WikiErrorView categoriesError, @NonNull TextView categoriesNoneFound,
      @NonNull RecyclerView categoriesRecycler, @NonNull ImageView categoriesThumbnail,
      @NonNull ProgressBar dialogCategoriesProgress) {
    this.rootView = rootView;
    this.categoriesDialogPageTitle = categoriesDialogPageTitle;
    this.categoriesDialogTitle = categoriesDialogTitle;
    this.categoriesError = categoriesError;
    this.categoriesNoneFound = categoriesNoneFound;
    this.categoriesRecycler = categoriesRecycler;
    this.categoriesThumbnail = categoriesThumbnail;
    this.dialogCategoriesProgress = dialogCategoriesProgress;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogCategoriesBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogCategoriesBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_categories, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogCategoriesBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.categories_dialog_page_title;
      TextView categoriesDialogPageTitle = ViewBindings.findChildViewById(rootView, id);
      if (categoriesDialogPageTitle == null) {
        break missingId;
      }

      id = R.id.categories_dialog_title;
      TextView categoriesDialogTitle = ViewBindings.findChildViewById(rootView, id);
      if (categoriesDialogTitle == null) {
        break missingId;
      }

      id = R.id.categories_error;
      WikiErrorView categoriesError = ViewBindings.findChildViewById(rootView, id);
      if (categoriesError == null) {
        break missingId;
      }

      id = R.id.categories_none_found;
      TextView categoriesNoneFound = ViewBindings.findChildViewById(rootView, id);
      if (categoriesNoneFound == null) {
        break missingId;
      }

      id = R.id.categories_recycler;
      RecyclerView categoriesRecycler = ViewBindings.findChildViewById(rootView, id);
      if (categoriesRecycler == null) {
        break missingId;
      }

      id = R.id.categories_thumbnail;
      ImageView categoriesThumbnail = ViewBindings.findChildViewById(rootView, id);
      if (categoriesThumbnail == null) {
        break missingId;
      }

      id = R.id.dialog_categories_progress;
      ProgressBar dialogCategoriesProgress = ViewBindings.findChildViewById(rootView, id);
      if (dialogCategoriesProgress == null) {
        break missingId;
      }

      return new DialogCategoriesBinding((FrameLayout) rootView, categoriesDialogPageTitle,
          categoriesDialogTitle, categoriesError, categoriesNoneFound, categoriesRecycler,
          categoriesThumbnail, dialogCategoriesProgress);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
