// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.gallery.GalleryThumbnailScrollView;
import org.wikipedia.page.linkpreview.LinkPreviewErrorView;

public final class DialogLinkPreviewBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final LinearLayout dialogLinkPreviewContainer;

  @NonNull
  public final LinearLayout dialogLinkPreviewContentContainer;

  @NonNull
  public final LinkPreviewErrorView dialogLinkPreviewErrorContainer;

  @NonNull
  public final TextView linkPreviewDistance;

  @NonNull
  public final MaterialButton linkPreviewEditButton;

  @NonNull
  public final TextView linkPreviewExtract;

  @NonNull
  public final ImageView linkPreviewOverflowButton;

  @NonNull
  public final ProgressBar linkPreviewProgress;

  @NonNull
  public final ImageView linkPreviewThumbnail;

  @NonNull
  public final GalleryThumbnailScrollView linkPreviewThumbnailGallery;

  @NonNull
  public final TextView linkPreviewTitle;

  @NonNull
  public final LinearLayout linkPreviewToolbar;

  private DialogLinkPreviewBinding(@NonNull FrameLayout rootView,
      @NonNull LinearLayout dialogLinkPreviewContainer,
      @NonNull LinearLayout dialogLinkPreviewContentContainer,
      @NonNull LinkPreviewErrorView dialogLinkPreviewErrorContainer,
      @NonNull TextView linkPreviewDistance, @NonNull MaterialButton linkPreviewEditButton,
      @NonNull TextView linkPreviewExtract, @NonNull ImageView linkPreviewOverflowButton,
      @NonNull ProgressBar linkPreviewProgress, @NonNull ImageView linkPreviewThumbnail,
      @NonNull GalleryThumbnailScrollView linkPreviewThumbnailGallery,
      @NonNull TextView linkPreviewTitle, @NonNull LinearLayout linkPreviewToolbar) {
    this.rootView = rootView;
    this.dialogLinkPreviewContainer = dialogLinkPreviewContainer;
    this.dialogLinkPreviewContentContainer = dialogLinkPreviewContentContainer;
    this.dialogLinkPreviewErrorContainer = dialogLinkPreviewErrorContainer;
    this.linkPreviewDistance = linkPreviewDistance;
    this.linkPreviewEditButton = linkPreviewEditButton;
    this.linkPreviewExtract = linkPreviewExtract;
    this.linkPreviewOverflowButton = linkPreviewOverflowButton;
    this.linkPreviewProgress = linkPreviewProgress;
    this.linkPreviewThumbnail = linkPreviewThumbnail;
    this.linkPreviewThumbnailGallery = linkPreviewThumbnailGallery;
    this.linkPreviewTitle = linkPreviewTitle;
    this.linkPreviewToolbar = linkPreviewToolbar;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogLinkPreviewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogLinkPreviewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_link_preview, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogLinkPreviewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.dialog_link_preview_container;
      LinearLayout dialogLinkPreviewContainer = ViewBindings.findChildViewById(rootView, id);
      if (dialogLinkPreviewContainer == null) {
        break missingId;
      }

      id = R.id.dialog_link_preview_content_container;
      LinearLayout dialogLinkPreviewContentContainer = ViewBindings.findChildViewById(rootView, id);
      if (dialogLinkPreviewContentContainer == null) {
        break missingId;
      }

      id = R.id.dialog_link_preview_error_container;
      LinkPreviewErrorView dialogLinkPreviewErrorContainer = ViewBindings.findChildViewById(rootView, id);
      if (dialogLinkPreviewErrorContainer == null) {
        break missingId;
      }

      id = R.id.link_preview_distance;
      TextView linkPreviewDistance = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewDistance == null) {
        break missingId;
      }

      id = R.id.linkPreviewEditButton;
      MaterialButton linkPreviewEditButton = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewEditButton == null) {
        break missingId;
      }

      id = R.id.link_preview_extract;
      TextView linkPreviewExtract = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewExtract == null) {
        break missingId;
      }

      id = R.id.link_preview_overflow_button;
      ImageView linkPreviewOverflowButton = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewOverflowButton == null) {
        break missingId;
      }

      id = R.id.link_preview_progress;
      ProgressBar linkPreviewProgress = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewProgress == null) {
        break missingId;
      }

      id = R.id.link_preview_thumbnail;
      ImageView linkPreviewThumbnail = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewThumbnail == null) {
        break missingId;
      }

      id = R.id.link_preview_thumbnail_gallery;
      GalleryThumbnailScrollView linkPreviewThumbnailGallery = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewThumbnailGallery == null) {
        break missingId;
      }

      id = R.id.link_preview_title;
      TextView linkPreviewTitle = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewTitle == null) {
        break missingId;
      }

      id = R.id.link_preview_toolbar;
      LinearLayout linkPreviewToolbar = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewToolbar == null) {
        break missingId;
      }

      return new DialogLinkPreviewBinding((FrameLayout) rootView, dialogLinkPreviewContainer,
          dialogLinkPreviewContentContainer, dialogLinkPreviewErrorContainer, linkPreviewDistance,
          linkPreviewEditButton, linkPreviewExtract, linkPreviewOverflowButton, linkPreviewProgress,
          linkPreviewThumbnail, linkPreviewThumbnailGallery, linkPreviewTitle, linkPreviewToolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
