// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class DialogEditNoticesBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final CheckBox editNoticeCheckbox;

  @NonNull
  public final ImageView editNoticeCloseButton;

  @NonNull
  public final TextView editNoticeHint;

  @NonNull
  public final ImageView editNoticeImage;

  @NonNull
  public final RecyclerView editNoticeRecycler;

  @NonNull
  public final TextView editNoticeTitle;

  private DialogEditNoticesBinding(@NonNull FrameLayout rootView,
      @NonNull CheckBox editNoticeCheckbox, @NonNull ImageView editNoticeCloseButton,
      @NonNull TextView editNoticeHint, @NonNull ImageView editNoticeImage,
      @NonNull RecyclerView editNoticeRecycler, @NonNull TextView editNoticeTitle) {
    this.rootView = rootView;
    this.editNoticeCheckbox = editNoticeCheckbox;
    this.editNoticeCloseButton = editNoticeCloseButton;
    this.editNoticeHint = editNoticeHint;
    this.editNoticeImage = editNoticeImage;
    this.editNoticeRecycler = editNoticeRecycler;
    this.editNoticeTitle = editNoticeTitle;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogEditNoticesBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogEditNoticesBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_edit_notices, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogEditNoticesBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.editNoticeCheckbox;
      CheckBox editNoticeCheckbox = ViewBindings.findChildViewById(rootView, id);
      if (editNoticeCheckbox == null) {
        break missingId;
      }

      id = R.id.editNoticeCloseButton;
      ImageView editNoticeCloseButton = ViewBindings.findChildViewById(rootView, id);
      if (editNoticeCloseButton == null) {
        break missingId;
      }

      id = R.id.editNoticeHint;
      TextView editNoticeHint = ViewBindings.findChildViewById(rootView, id);
      if (editNoticeHint == null) {
        break missingId;
      }

      id = R.id.editNoticeImage;
      ImageView editNoticeImage = ViewBindings.findChildViewById(rootView, id);
      if (editNoticeImage == null) {
        break missingId;
      }

      id = R.id.editNoticeRecycler;
      RecyclerView editNoticeRecycler = ViewBindings.findChildViewById(rootView, id);
      if (editNoticeRecycler == null) {
        break missingId;
      }

      id = R.id.editNoticeTitle;
      TextView editNoticeTitle = ViewBindings.findChildViewById(rootView, id);
      if (editNoticeTitle == null) {
        break missingId;
      }

      return new DialogEditNoticesBinding((FrameLayout) rootView, editNoticeCheckbox,
          editNoticeCloseButton, editNoticeHint, editNoticeImage, editNoticeRecycler,
          editNoticeTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
