// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.materialswitch.MaterialSwitch;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.PlainPasteEditText;

public final class DialogInsertMediaSizeBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextInputLayout imageSizeCustomHeightLayout;

  @NonNull
  public final PlainPasteEditText imageSizeCustomHeightText;

  @NonNull
  public final MaterialSwitch imageSizeCustomSwitch;

  @NonNull
  public final TextInputLayout imageSizeCustomWidthLayout;

  @NonNull
  public final PlainPasteEditText imageSizeCustomWidthText;

  private DialogInsertMediaSizeBinding(@NonNull LinearLayout rootView,
      @NonNull TextInputLayout imageSizeCustomHeightLayout,
      @NonNull PlainPasteEditText imageSizeCustomHeightText,
      @NonNull MaterialSwitch imageSizeCustomSwitch,
      @NonNull TextInputLayout imageSizeCustomWidthLayout,
      @NonNull PlainPasteEditText imageSizeCustomWidthText) {
    this.rootView = rootView;
    this.imageSizeCustomHeightLayout = imageSizeCustomHeightLayout;
    this.imageSizeCustomHeightText = imageSizeCustomHeightText;
    this.imageSizeCustomSwitch = imageSizeCustomSwitch;
    this.imageSizeCustomWidthLayout = imageSizeCustomWidthLayout;
    this.imageSizeCustomWidthText = imageSizeCustomWidthText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogInsertMediaSizeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogInsertMediaSizeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_insert_media_size, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogInsertMediaSizeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageSizeCustomHeightLayout;
      TextInputLayout imageSizeCustomHeightLayout = ViewBindings.findChildViewById(rootView, id);
      if (imageSizeCustomHeightLayout == null) {
        break missingId;
      }

      id = R.id.imageSizeCustomHeightText;
      PlainPasteEditText imageSizeCustomHeightText = ViewBindings.findChildViewById(rootView, id);
      if (imageSizeCustomHeightText == null) {
        break missingId;
      }

      id = R.id.imageSizeCustomSwitch;
      MaterialSwitch imageSizeCustomSwitch = ViewBindings.findChildViewById(rootView, id);
      if (imageSizeCustomSwitch == null) {
        break missingId;
      }

      id = R.id.imageSizeCustomWidthLayout;
      TextInputLayout imageSizeCustomWidthLayout = ViewBindings.findChildViewById(rootView, id);
      if (imageSizeCustomWidthLayout == null) {
        break missingId;
      }

      id = R.id.imageSizeCustomWidthText;
      PlainPasteEditText imageSizeCustomWidthText = ViewBindings.findChildViewById(rootView, id);
      if (imageSizeCustomWidthText == null) {
        break missingId;
      }

      return new DialogInsertMediaSizeBinding((LinearLayout) rootView, imageSizeCustomHeightLayout,
          imageSizeCustomHeightText, imageSizeCustomSwitch, imageSizeCustomWidthLayout,
          imageSizeCustomWidthText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
