// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.PlainPasteEditText;

public final class DialogUndoEditBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final PlainPasteEditText textInput;

  @NonNull
  public final TextInputLayout textInputContainer;

  private DialogUndoEditBinding(@NonNull ScrollView rootView, @NonNull PlainPasteEditText textInput,
      @NonNull TextInputLayout textInputContainer) {
    this.rootView = rootView;
    this.textInput = textInput;
    this.textInputContainer = textInputContainer;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogUndoEditBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogUndoEditBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_undo_edit, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogUndoEditBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.text_input;
      PlainPasteEditText textInput = ViewBindings.findChildViewById(rootView, id);
      if (textInput == null) {
        break missingId;
      }

      id = R.id.text_input_container;
      TextInputLayout textInputContainer = ViewBindings.findChildViewById(rootView, id);
      if (textInputContainer == null) {
        break missingId;
      }

      return new DialogUndoEditBinding((ScrollView) rootView, textInput, textInputContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
