// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.PlainPasteEditText;
import org.wikipedia.views.WikiCardView;

public final class FragmentInsertMediaSettingsBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button advancedSettings;

  @NonNull
  public final WikiCardView imageInfoContainer;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final ScrollView insertMediaPreviewContainer;

  @NonNull
  public final PlainPasteEditText mediaAlternativeText;

  @NonNull
  public final TextInputLayout mediaAlternativeTextLayout;

  @NonNull
  public final TextInputLayout mediaCaptionLayout;

  @NonNull
  public final PlainPasteEditText mediaCaptionText;

  @NonNull
  public final TextView mediaDescription;

  @NonNull
  public final TextView mediaTitle;

  private FragmentInsertMediaSettingsBinding(@NonNull ScrollView rootView,
      @NonNull Button advancedSettings, @NonNull WikiCardView imageInfoContainer,
      @NonNull ImageView imageView, @NonNull ScrollView insertMediaPreviewContainer,
      @NonNull PlainPasteEditText mediaAlternativeText,
      @NonNull TextInputLayout mediaAlternativeTextLayout,
      @NonNull TextInputLayout mediaCaptionLayout, @NonNull PlainPasteEditText mediaCaptionText,
      @NonNull TextView mediaDescription, @NonNull TextView mediaTitle) {
    this.rootView = rootView;
    this.advancedSettings = advancedSettings;
    this.imageInfoContainer = imageInfoContainer;
    this.imageView = imageView;
    this.insertMediaPreviewContainer = insertMediaPreviewContainer;
    this.mediaAlternativeText = mediaAlternativeText;
    this.mediaAlternativeTextLayout = mediaAlternativeTextLayout;
    this.mediaCaptionLayout = mediaCaptionLayout;
    this.mediaCaptionText = mediaCaptionText;
    this.mediaDescription = mediaDescription;
    this.mediaTitle = mediaTitle;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentInsertMediaSettingsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentInsertMediaSettingsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_insert_media_settings, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentInsertMediaSettingsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.advancedSettings;
      Button advancedSettings = ViewBindings.findChildViewById(rootView, id);
      if (advancedSettings == null) {
        break missingId;
      }

      id = R.id.imageInfoContainer;
      WikiCardView imageInfoContainer = ViewBindings.findChildViewById(rootView, id);
      if (imageInfoContainer == null) {
        break missingId;
      }

      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      ScrollView insertMediaPreviewContainer = (ScrollView) rootView;

      id = R.id.mediaAlternativeText;
      PlainPasteEditText mediaAlternativeText = ViewBindings.findChildViewById(rootView, id);
      if (mediaAlternativeText == null) {
        break missingId;
      }

      id = R.id.mediaAlternativeTextLayout;
      TextInputLayout mediaAlternativeTextLayout = ViewBindings.findChildViewById(rootView, id);
      if (mediaAlternativeTextLayout == null) {
        break missingId;
      }

      id = R.id.mediaCaptionLayout;
      TextInputLayout mediaCaptionLayout = ViewBindings.findChildViewById(rootView, id);
      if (mediaCaptionLayout == null) {
        break missingId;
      }

      id = R.id.mediaCaptionText;
      PlainPasteEditText mediaCaptionText = ViewBindings.findChildViewById(rootView, id);
      if (mediaCaptionText == null) {
        break missingId;
      }

      id = R.id.mediaDescription;
      TextView mediaDescription = ViewBindings.findChildViewById(rootView, id);
      if (mediaDescription == null) {
        break missingId;
      }

      id = R.id.mediaTitle;
      TextView mediaTitle = ViewBindings.findChildViewById(rootView, id);
      if (mediaTitle == null) {
        break missingId;
      }

      return new FragmentInsertMediaSettingsBinding((ScrollView) rootView, advancedSettings,
          imageInfoContainer, imageView, insertMediaPreviewContainer, mediaAlternativeText,
          mediaAlternativeTextLayout, mediaCaptionLayout, mediaCaptionText, mediaDescription,
          mediaTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
