// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import androidx.viewpager2.widget.ViewPager2;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.navtab.NavTabLayout;

public final class FragmentMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CoordinatorLayout fragmentMainCoordinator;

  @NonNull
  public final View mainNavTabBorder;

  @NonNull
  public final NavTabLayout mainNavTabLayout;

  @NonNull
  public final ViewPager2 mainViewPager;

  private FragmentMainBinding(@NonNull ConstraintLayout rootView,
      @NonNull CoordinatorLayout fragmentMainCoordinator, @NonNull View mainNavTabBorder,
      @NonNull NavTabLayout mainNavTabLayout, @NonNull ViewPager2 mainViewPager) {
    this.rootView = rootView;
    this.fragmentMainCoordinator = fragmentMainCoordinator;
    this.mainNavTabBorder = mainNavTabBorder;
    this.mainNavTabLayout = mainNavTabLayout;
    this.mainViewPager = mainViewPager;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.fragment_main_coordinator;
      CoordinatorLayout fragmentMainCoordinator = ViewBindings.findChildViewById(rootView, id);
      if (fragmentMainCoordinator == null) {
        break missingId;
      }

      id = R.id.main_nav_tab_border;
      View mainNavTabBorder = ViewBindings.findChildViewById(rootView, id);
      if (mainNavTabBorder == null) {
        break missingId;
      }

      id = R.id.main_nav_tab_layout;
      NavTabLayout mainNavTabLayout = ViewBindings.findChildViewById(rootView, id);
      if (mainNavTabLayout == null) {
        break missingId;
      }

      id = R.id.main_view_pager;
      ViewPager2 mainViewPager = ViewBindings.findChildViewById(rootView, id);
      if (mainViewPager == null) {
        break missingId;
      }

      return new FragmentMainBinding((ConstraintLayout) rootView, fragmentMainCoordinator,
          mainNavTabBorder, mainNavTabLayout, mainViewPager);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
