// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ProgressBar;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiArticleCardView;
import org.wikipedia.views.WikiCardView;
import org.wikipedia.views.WikiErrorView;

public final class FragmentRandomItemBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final WikiCardView cardView;

  @NonNull
  public final WikiErrorView randomItemErrorView;

  @NonNull
  public final ProgressBar randomItemProgress;

  @NonNull
  public final WikiArticleCardView randomItemWikiArticleCardView;

  private FragmentRandomItemBinding(@NonNull FrameLayout rootView, @NonNull WikiCardView cardView,
      @NonNull WikiErrorView randomItemErrorView, @NonNull ProgressBar randomItemProgress,
      @NonNull WikiArticleCardView randomItemWikiArticleCardView) {
    this.rootView = rootView;
    this.cardView = cardView;
    this.randomItemErrorView = randomItemErrorView;
    this.randomItemProgress = randomItemProgress;
    this.randomItemWikiArticleCardView = randomItemWikiArticleCardView;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentRandomItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentRandomItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_random_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentRandomItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.card_view;
      WikiCardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.random_item_error_view;
      WikiErrorView randomItemErrorView = ViewBindings.findChildViewById(rootView, id);
      if (randomItemErrorView == null) {
        break missingId;
      }

      id = R.id.random_item_progress;
      ProgressBar randomItemProgress = ViewBindings.findChildViewById(rootView, id);
      if (randomItemProgress == null) {
        break missingId;
      }

      id = R.id.random_item_wiki_article_card_view;
      WikiArticleCardView randomItemWikiArticleCardView = ViewBindings.findChildViewById(rootView, id);
      if (randomItemWikiArticleCardView == null) {
        break missingId;
      }

      return new FragmentRandomItemBinding((FrameLayout) rootView, cardView, randomItemErrorView,
          randomItemProgress, randomItemWikiArticleCardView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
