// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.CollapsingToolbarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.AppTextView;
import org.wikipedia.views.FaceAndColorDetectImageView;

public final class FragmentNewsBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final View gradientView;

  @NonNull
  public final FaceAndColorDetectImageView headerImageView;

  @NonNull
  public final RecyclerView newsStoryItemsRecyclerview;

  @NonNull
  public final AppTextView storyTextView;

  @NonNull
  public final MaterialToolbar toolbar;

  @NonNull
  public final CollapsingToolbarLayout toolbarContainer;

  private FragmentNewsBinding(@NonNull CoordinatorLayout rootView,
      @NonNull AppBarLayout appBarLayout, @NonNull View gradientView,
      @NonNull FaceAndColorDetectImageView headerImageView,
      @NonNull RecyclerView newsStoryItemsRecyclerview, @NonNull AppTextView storyTextView,
      @NonNull MaterialToolbar toolbar, @NonNull CollapsingToolbarLayout toolbarContainer) {
    this.rootView = rootView;
    this.appBarLayout = appBarLayout;
    this.gradientView = gradientView;
    this.headerImageView = headerImageView;
    this.newsStoryItemsRecyclerview = newsStoryItemsRecyclerview;
    this.storyTextView = storyTextView;
    this.toolbar = toolbar;
    this.toolbarContainer = toolbarContainer;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentNewsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentNewsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_news, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentNewsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.app_bar_layout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.gradient_view;
      View gradientView = ViewBindings.findChildViewById(rootView, id);
      if (gradientView == null) {
        break missingId;
      }

      id = R.id.header_image_view;
      FaceAndColorDetectImageView headerImageView = ViewBindings.findChildViewById(rootView, id);
      if (headerImageView == null) {
        break missingId;
      }

      id = R.id.news_story_items_recyclerview;
      RecyclerView newsStoryItemsRecyclerview = ViewBindings.findChildViewById(rootView, id);
      if (newsStoryItemsRecyclerview == null) {
        break missingId;
      }

      id = R.id.story_text_view;
      AppTextView storyTextView = ViewBindings.findChildViewById(rootView, id);
      if (storyTextView == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.toolbar_container;
      CollapsingToolbarLayout toolbarContainer = ViewBindings.findChildViewById(rootView, id);
      if (toolbarContainer == null) {
        break missingId;
      }

      return new FragmentNewsBinding((CoordinatorLayout) rootView, appBarLayout, gradientView,
          headerImageView, newsStoryItemsRecyclerview, storyTextView, toolbar, toolbarContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
