// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import androidx.viewpager2.widget.ViewPager2;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class FragmentRandomBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final ImageView randomBackButton;

  @NonNull
  public final CoordinatorLayout randomCoordinatorLayout;

  @NonNull
  public final ViewPager2 randomItemPager;

  @NonNull
  public final FloatingActionButton randomNextButton;

  @NonNull
  public final ImageView randomSaveButton;

  private FragmentRandomBinding(@NonNull CoordinatorLayout rootView,
      @NonNull ImageView randomBackButton, @NonNull CoordinatorLayout randomCoordinatorLayout,
      @NonNull ViewPager2 randomItemPager, @NonNull FloatingActionButton randomNextButton,
      @NonNull ImageView randomSaveButton) {
    this.rootView = rootView;
    this.randomBackButton = randomBackButton;
    this.randomCoordinatorLayout = randomCoordinatorLayout;
    this.randomItemPager = randomItemPager;
    this.randomNextButton = randomNextButton;
    this.randomSaveButton = randomSaveButton;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentRandomBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentRandomBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_random, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentRandomBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.random_back_button;
      ImageView randomBackButton = ViewBindings.findChildViewById(rootView, id);
      if (randomBackButton == null) {
        break missingId;
      }

      CoordinatorLayout randomCoordinatorLayout = (CoordinatorLayout) rootView;

      id = R.id.random_item_pager;
      ViewPager2 randomItemPager = ViewBindings.findChildViewById(rootView, id);
      if (randomItemPager == null) {
        break missingId;
      }

      id = R.id.random_next_button;
      FloatingActionButton randomNextButton = ViewBindings.findChildViewById(rootView, id);
      if (randomNextButton == null) {
        break missingId;
      }

      id = R.id.random_save_button;
      ImageView randomSaveButton = ViewBindings.findChildViewById(rootView, id);
      if (randomSaveButton == null) {
        break missingId;
      }

      return new FragmentRandomBinding((CoordinatorLayout) rootView, randomBackButton,
          randomCoordinatorLayout, randomItemPager, randomNextButton, randomSaveButton);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
