// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.FaceAndColorDetectImageView;
import org.wikipedia.views.GoneIfEmptyTextView;
import org.wikipedia.views.WikiCardView;
import org.wikipedia.views.WikiErrorView;

public final class FragmentSuggestedEditsCardItemBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final View articleDescriptionPlaceHolder1;

  @NonNull
  public final View articleDescriptionPlaceHolder2;

  @NonNull
  public final MaterialButton callToActionButton;

  @NonNull
  public final LinearLayout cardItemContainer;

  @NonNull
  public final WikiCardView cardView;

  @NonNull
  public final View divider;

  @NonNull
  public final WikiErrorView seCardErrorView;

  @NonNull
  public final ProgressBar seFeedCardProgressBar;

  @NonNull
  public final LinearLayout viewArticleContainer;

  @NonNull
  public final TextView viewArticleExtract;

  @NonNull
  public final FaceAndColorDetectImageView viewArticleImage;

  @NonNull
  public final GoneIfEmptyTextView viewArticleSubtitle;

  @NonNull
  public final TextView viewArticleTitle;

  private FragmentSuggestedEditsCardItemBinding(@NonNull FrameLayout rootView,
      @NonNull View articleDescriptionPlaceHolder1, @NonNull View articleDescriptionPlaceHolder2,
      @NonNull MaterialButton callToActionButton, @NonNull LinearLayout cardItemContainer,
      @NonNull WikiCardView cardView, @NonNull View divider, @NonNull WikiErrorView seCardErrorView,
      @NonNull ProgressBar seFeedCardProgressBar, @NonNull LinearLayout viewArticleContainer,
      @NonNull TextView viewArticleExtract, @NonNull FaceAndColorDetectImageView viewArticleImage,
      @NonNull GoneIfEmptyTextView viewArticleSubtitle, @NonNull TextView viewArticleTitle) {
    this.rootView = rootView;
    this.articleDescriptionPlaceHolder1 = articleDescriptionPlaceHolder1;
    this.articleDescriptionPlaceHolder2 = articleDescriptionPlaceHolder2;
    this.callToActionButton = callToActionButton;
    this.cardItemContainer = cardItemContainer;
    this.cardView = cardView;
    this.divider = divider;
    this.seCardErrorView = seCardErrorView;
    this.seFeedCardProgressBar = seFeedCardProgressBar;
    this.viewArticleContainer = viewArticleContainer;
    this.viewArticleExtract = viewArticleExtract;
    this.viewArticleImage = viewArticleImage;
    this.viewArticleSubtitle = viewArticleSubtitle;
    this.viewArticleTitle = viewArticleTitle;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentSuggestedEditsCardItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentSuggestedEditsCardItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_suggested_edits_card_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentSuggestedEditsCardItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.articleDescriptionPlaceHolder1;
      View articleDescriptionPlaceHolder1 = ViewBindings.findChildViewById(rootView, id);
      if (articleDescriptionPlaceHolder1 == null) {
        break missingId;
      }

      id = R.id.articleDescriptionPlaceHolder2;
      View articleDescriptionPlaceHolder2 = ViewBindings.findChildViewById(rootView, id);
      if (articleDescriptionPlaceHolder2 == null) {
        break missingId;
      }

      id = R.id.callToActionButton;
      MaterialButton callToActionButton = ViewBindings.findChildViewById(rootView, id);
      if (callToActionButton == null) {
        break missingId;
      }

      id = R.id.cardItemContainer;
      LinearLayout cardItemContainer = ViewBindings.findChildViewById(rootView, id);
      if (cardItemContainer == null) {
        break missingId;
      }

      id = R.id.cardView;
      WikiCardView cardView = ViewBindings.findChildViewById(rootView, id);
      if (cardView == null) {
        break missingId;
      }

      id = R.id.divider;
      View divider = ViewBindings.findChildViewById(rootView, id);
      if (divider == null) {
        break missingId;
      }

      id = R.id.seCardErrorView;
      WikiErrorView seCardErrorView = ViewBindings.findChildViewById(rootView, id);
      if (seCardErrorView == null) {
        break missingId;
      }

      id = R.id.seFeedCardProgressBar;
      ProgressBar seFeedCardProgressBar = ViewBindings.findChildViewById(rootView, id);
      if (seFeedCardProgressBar == null) {
        break missingId;
      }

      id = R.id.viewArticleContainer;
      LinearLayout viewArticleContainer = ViewBindings.findChildViewById(rootView, id);
      if (viewArticleContainer == null) {
        break missingId;
      }

      id = R.id.viewArticleExtract;
      TextView viewArticleExtract = ViewBindings.findChildViewById(rootView, id);
      if (viewArticleExtract == null) {
        break missingId;
      }

      id = R.id.viewArticleImage;
      FaceAndColorDetectImageView viewArticleImage = ViewBindings.findChildViewById(rootView, id);
      if (viewArticleImage == null) {
        break missingId;
      }

      id = R.id.viewArticleSubtitle;
      GoneIfEmptyTextView viewArticleSubtitle = ViewBindings.findChildViewById(rootView, id);
      if (viewArticleSubtitle == null) {
        break missingId;
      }

      id = R.id.viewArticleTitle;
      TextView viewArticleTitle = ViewBindings.findChildViewById(rootView, id);
      if (viewArticleTitle == null) {
        break missingId;
      }

      return new FragmentSuggestedEditsCardItemBinding((FrameLayout) rootView,
          articleDescriptionPlaceHolder1, articleDescriptionPlaceHolder2, callToActionButton,
          cardItemContainer, cardView, divider, seCardErrorView, seFeedCardProgressBar,
          viewArticleContainer, viewArticleExtract, viewArticleImage, viewArticleSubtitle,
          viewArticleTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
