// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiErrorView;

public final class FragmentSearchResultsBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final WikiErrorView searchErrorView;

  @NonNull
  public final FrameLayout searchResultsDisplay;

  @NonNull
  public final RecyclerView searchResultsList;

  private FragmentSearchResultsBinding(@NonNull FrameLayout rootView,
      @NonNull WikiErrorView searchErrorView, @NonNull FrameLayout searchResultsDisplay,
      @NonNull RecyclerView searchResultsList) {
    this.rootView = rootView;
    this.searchErrorView = searchErrorView;
    this.searchResultsDisplay = searchResultsDisplay;
    this.searchResultsList = searchResultsList;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentSearchResultsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentSearchResultsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_search_results, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentSearchResultsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.search_error_view;
      WikiErrorView searchErrorView = ViewBindings.findChildViewById(rootView, id);
      if (searchErrorView == null) {
        break missingId;
      }

      FrameLayout searchResultsDisplay = (FrameLayout) rootView;

      id = R.id.search_results_list;
      RecyclerView searchResultsList = ViewBindings.findChildViewById(rootView, id);
      if (searchResultsList == null) {
        break missingId;
      }

      return new FragmentSearchResultsBinding((FrameLayout) rootView, searchErrorView,
          searchResultsDisplay, searchResultsList);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
