// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButton;
import com.google.android.material.textfield.MaterialAutoCompleteTextView;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class FragmentPreviewSummaryBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final ScrollView editSummaryContainer;

  @NonNull
  public final LinearLayout editSummaryTagsContainer;

  @NonNull
  public final MaterialAutoCompleteTextView editSummaryText;

  @NonNull
  public final TextInputLayout editSummaryTextLayout;

  @NonNull
  public final InflateEditAccountFooterBinding footerContainer;

  @NonNull
  public final MaterialButton learnMoreButton;

  @NonNull
  public final CheckBox minorEditCheckBox;

  @NonNull
  public final ImageView minorEditHelpButton;

  @NonNull
  public final CheckBox watchPageCheckBox;

  @NonNull
  public final ImageView watchPageHelpButton;

  private FragmentPreviewSummaryBinding(@NonNull ScrollView rootView,
      @NonNull ScrollView editSummaryContainer, @NonNull LinearLayout editSummaryTagsContainer,
      @NonNull MaterialAutoCompleteTextView editSummaryText,
      @NonNull TextInputLayout editSummaryTextLayout,
      @NonNull InflateEditAccountFooterBinding footerContainer,
      @NonNull MaterialButton learnMoreButton, @NonNull CheckBox minorEditCheckBox,
      @NonNull ImageView minorEditHelpButton, @NonNull CheckBox watchPageCheckBox,
      @NonNull ImageView watchPageHelpButton) {
    this.rootView = rootView;
    this.editSummaryContainer = editSummaryContainer;
    this.editSummaryTagsContainer = editSummaryTagsContainer;
    this.editSummaryText = editSummaryText;
    this.editSummaryTextLayout = editSummaryTextLayout;
    this.footerContainer = footerContainer;
    this.learnMoreButton = learnMoreButton;
    this.minorEditCheckBox = minorEditCheckBox;
    this.minorEditHelpButton = minorEditHelpButton;
    this.watchPageCheckBox = watchPageCheckBox;
    this.watchPageHelpButton = watchPageHelpButton;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentPreviewSummaryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentPreviewSummaryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_preview_summary, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentPreviewSummaryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      ScrollView editSummaryContainer = (ScrollView) rootView;

      id = R.id.editSummaryTagsContainer;
      LinearLayout editSummaryTagsContainer = ViewBindings.findChildViewById(rootView, id);
      if (editSummaryTagsContainer == null) {
        break missingId;
      }

      id = R.id.editSummaryText;
      MaterialAutoCompleteTextView editSummaryText = ViewBindings.findChildViewById(rootView, id);
      if (editSummaryText == null) {
        break missingId;
      }

      id = R.id.editSummaryTextLayout;
      TextInputLayout editSummaryTextLayout = ViewBindings.findChildViewById(rootView, id);
      if (editSummaryTextLayout == null) {
        break missingId;
      }

      id = R.id.footerContainer;
      View footerContainer = ViewBindings.findChildViewById(rootView, id);
      if (footerContainer == null) {
        break missingId;
      }
      InflateEditAccountFooterBinding binding_footerContainer = InflateEditAccountFooterBinding.bind(footerContainer);

      id = R.id.learnMoreButton;
      MaterialButton learnMoreButton = ViewBindings.findChildViewById(rootView, id);
      if (learnMoreButton == null) {
        break missingId;
      }

      id = R.id.minorEditCheckBox;
      CheckBox minorEditCheckBox = ViewBindings.findChildViewById(rootView, id);
      if (minorEditCheckBox == null) {
        break missingId;
      }

      id = R.id.minorEditHelpButton;
      ImageView minorEditHelpButton = ViewBindings.findChildViewById(rootView, id);
      if (minorEditHelpButton == null) {
        break missingId;
      }

      id = R.id.watchPageCheckBox;
      CheckBox watchPageCheckBox = ViewBindings.findChildViewById(rootView, id);
      if (watchPageCheckBox == null) {
        break missingId;
      }

      id = R.id.watchPageHelpButton;
      ImageView watchPageHelpButton = ViewBindings.findChildViewById(rootView, id);
      if (watchPageHelpButton == null) {
        break missingId;
      }

      return new FragmentPreviewSummaryBinding((ScrollView) rootView, editSummaryContainer,
          editSummaryTagsContainer, editSummaryText, editSummaryTextLayout, binding_footerContainer,
          learnMoreButton, minorEditCheckBox, minorEditHelpButton, watchPageCheckBox,
          watchPageHelpButton);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
