// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.checkbox.MaterialCheckBox;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class FragmentSuggestedEditsImageRecsDialogBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final MaterialCheckBox checkBox1;

  @NonNull
  public final MaterialCheckBox checkBox2;

  @NonNull
  public final MaterialCheckBox checkBox3;

  @NonNull
  public final MaterialCheckBox checkBox4;

  @NonNull
  public final MaterialCheckBox checkBox5;

  @NonNull
  public final MaterialCheckBox checkBox6;

  @NonNull
  public final LinearLayout imageRecommendationDialogContainer;

  @NonNull
  public final TextView instructionSubText;

  private FragmentSuggestedEditsImageRecsDialogBinding(@NonNull ScrollView rootView,
      @NonNull MaterialCheckBox checkBox1, @NonNull MaterialCheckBox checkBox2,
      @NonNull MaterialCheckBox checkBox3, @NonNull MaterialCheckBox checkBox4,
      @NonNull MaterialCheckBox checkBox5, @NonNull MaterialCheckBox checkBox6,
      @NonNull LinearLayout imageRecommendationDialogContainer,
      @NonNull TextView instructionSubText) {
    this.rootView = rootView;
    this.checkBox1 = checkBox1;
    this.checkBox2 = checkBox2;
    this.checkBox3 = checkBox3;
    this.checkBox4 = checkBox4;
    this.checkBox5 = checkBox5;
    this.checkBox6 = checkBox6;
    this.imageRecommendationDialogContainer = imageRecommendationDialogContainer;
    this.instructionSubText = instructionSubText;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentSuggestedEditsImageRecsDialogBinding inflate(
      @NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentSuggestedEditsImageRecsDialogBinding inflate(
      @NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_suggested_edits_image_recs_dialog, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentSuggestedEditsImageRecsDialogBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.checkBox1;
      MaterialCheckBox checkBox1 = ViewBindings.findChildViewById(rootView, id);
      if (checkBox1 == null) {
        break missingId;
      }

      id = R.id.checkBox2;
      MaterialCheckBox checkBox2 = ViewBindings.findChildViewById(rootView, id);
      if (checkBox2 == null) {
        break missingId;
      }

      id = R.id.checkBox3;
      MaterialCheckBox checkBox3 = ViewBindings.findChildViewById(rootView, id);
      if (checkBox3 == null) {
        break missingId;
      }

      id = R.id.checkBox4;
      MaterialCheckBox checkBox4 = ViewBindings.findChildViewById(rootView, id);
      if (checkBox4 == null) {
        break missingId;
      }

      id = R.id.checkBox5;
      MaterialCheckBox checkBox5 = ViewBindings.findChildViewById(rootView, id);
      if (checkBox5 == null) {
        break missingId;
      }

      id = R.id.checkBox6;
      MaterialCheckBox checkBox6 = ViewBindings.findChildViewById(rootView, id);
      if (checkBox6 == null) {
        break missingId;
      }

      id = R.id.imageRecommendationDialogContainer;
      LinearLayout imageRecommendationDialogContainer = ViewBindings.findChildViewById(rootView, id);
      if (imageRecommendationDialogContainer == null) {
        break missingId;
      }

      id = R.id.instructionSubText;
      TextView instructionSubText = ViewBindings.findChildViewById(rootView, id);
      if (instructionSubText == null) {
        break missingId;
      }

      return new FragmentSuggestedEditsImageRecsDialogBinding((ScrollView) rootView, checkBox1,
          checkBox2, checkBox3, checkBox4, checkBox5, checkBox6, imageRecommendationDialogContainer,
          instructionSubText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
