// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import org.wikipedia.R;
import org.wikipedia.descriptions.DescriptionEditView;

public final class FragmentDescriptionEditBinding implements ViewBinding {
  @NonNull
  private final DescriptionEditView rootView;

  @NonNull
  public final DescriptionEditView fragmentDescriptionEditView;

  private FragmentDescriptionEditBinding(@NonNull DescriptionEditView rootView,
      @NonNull DescriptionEditView fragmentDescriptionEditView) {
    this.rootView = rootView;
    this.fragmentDescriptionEditView = fragmentDescriptionEditView;
  }

  @Override
  @NonNull
  public DescriptionEditView getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentDescriptionEditBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentDescriptionEditBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_description_edit, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentDescriptionEditBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    DescriptionEditView fragmentDescriptionEditView = (DescriptionEditView) rootView;

    return new FragmentDescriptionEditBinding((DescriptionEditView) rootView,
        fragmentDescriptionEditView);
  }
}
