// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import androidx.viewpager2.widget.ViewPager2;
import com.google.android.material.tabs.TabLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.AppTextView;

public final class FragmentReferencesPagerBinding implements ViewBinding {
  @NonNull
  private final NestedScrollView rootView;

  @NonNull
  public final View indicatorDivider;

  @NonNull
  public final TabLayout pageIndicatorView;

  @NonNull
  public final ViewPager2 referencePager;

  @NonNull
  public final AppTextView referenceTitleText;

  private FragmentReferencesPagerBinding(@NonNull NestedScrollView rootView,
      @NonNull View indicatorDivider, @NonNull TabLayout pageIndicatorView,
      @NonNull ViewPager2 referencePager, @NonNull AppTextView referenceTitleText) {
    this.rootView = rootView;
    this.indicatorDivider = indicatorDivider;
    this.pageIndicatorView = pageIndicatorView;
    this.referencePager = referencePager;
    this.referenceTitleText = referenceTitleText;
  }

  @Override
  @NonNull
  public NestedScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentReferencesPagerBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentReferencesPagerBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_references_pager, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentReferencesPagerBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.indicator_divider;
      View indicatorDivider = ViewBindings.findChildViewById(rootView, id);
      if (indicatorDivider == null) {
        break missingId;
      }

      id = R.id.page_indicator_view;
      TabLayout pageIndicatorView = ViewBindings.findChildViewById(rootView, id);
      if (pageIndicatorView == null) {
        break missingId;
      }

      id = R.id.reference_pager;
      ViewPager2 referencePager = ViewBindings.findChildViewById(rootView, id);
      if (referencePager == null) {
        break missingId;
      }

      id = R.id.reference_title_text;
      AppTextView referenceTitleText = ViewBindings.findChildViewById(rootView, id);
      if (referenceTitleText == null) {
        break missingId;
      }

      return new FragmentReferencesPagerBinding((NestedScrollView) rootView, indicatorDivider,
          pageIndicatorView, referencePager, referenceTitleText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
