// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.feed.view.FeedView;
import org.wikipedia.views.WikiSwipeRefreshLayout;

public final class FragmentFeedBinding implements ViewBinding {
  @NonNull
  private final WikiSwipeRefreshLayout rootView;

  @NonNull
  public final Button customizeButton;

  @NonNull
  public final LinearLayout emptyContainer;

  @NonNull
  public final FeedView feedView;

  @NonNull
  public final WikiSwipeRefreshLayout swipeRefreshLayout;

  private FragmentFeedBinding(@NonNull WikiSwipeRefreshLayout rootView,
      @NonNull Button customizeButton, @NonNull LinearLayout emptyContainer,
      @NonNull FeedView feedView, @NonNull WikiSwipeRefreshLayout swipeRefreshLayout) {
    this.rootView = rootView;
    this.customizeButton = customizeButton;
    this.emptyContainer = emptyContainer;
    this.feedView = feedView;
    this.swipeRefreshLayout = swipeRefreshLayout;
  }

  @Override
  @NonNull
  public WikiSwipeRefreshLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentFeedBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentFeedBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_feed, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentFeedBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.customize_button;
      Button customizeButton = ViewBindings.findChildViewById(rootView, id);
      if (customizeButton == null) {
        break missingId;
      }

      id = R.id.empty_container;
      LinearLayout emptyContainer = ViewBindings.findChildViewById(rootView, id);
      if (emptyContainer == null) {
        break missingId;
      }

      id = R.id.feed_view;
      FeedView feedView = ViewBindings.findChildViewById(rootView, id);
      if (feedView == null) {
        break missingId;
      }

      WikiSwipeRefreshLayout swipeRefreshLayout = (WikiSwipeRefreshLayout) rootView;

      return new FragmentFeedBinding((WikiSwipeRefreshLayout) rootView, customizeButton,
          emptyContainer, feedView, swipeRefreshLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
