// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class GroupFindReferencesInPageBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout findInPageContainer;

  @NonNull
  public final ImageView findInPageNext;

  @NonNull
  public final ImageView findInPagePrev;

  @NonNull
  public final TextView referenceCount;

  @NonNull
  public final TextView referenceLabel;

  private GroupFindReferencesInPageBinding(@NonNull LinearLayout rootView,
      @NonNull LinearLayout findInPageContainer, @NonNull ImageView findInPageNext,
      @NonNull ImageView findInPagePrev, @NonNull TextView referenceCount,
      @NonNull TextView referenceLabel) {
    this.rootView = rootView;
    this.findInPageContainer = findInPageContainer;
    this.findInPageNext = findInPageNext;
    this.findInPagePrev = findInPagePrev;
    this.referenceCount = referenceCount;
    this.referenceLabel = referenceLabel;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static GroupFindReferencesInPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static GroupFindReferencesInPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.group_find_references_in_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static GroupFindReferencesInPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      LinearLayout findInPageContainer = (LinearLayout) rootView;

      id = R.id.find_in_page_next;
      ImageView findInPageNext = ViewBindings.findChildViewById(rootView, id);
      if (findInPageNext == null) {
        break missingId;
      }

      id = R.id.find_in_page_prev;
      ImageView findInPagePrev = ViewBindings.findChildViewById(rootView, id);
      if (findInPagePrev == null) {
        break missingId;
      }

      id = R.id.reference_count;
      TextView referenceCount = ViewBindings.findChildViewById(rootView, id);
      if (referenceCount == null) {
        break missingId;
      }

      id = R.id.reference_label;
      TextView referenceLabel = ViewBindings.findChildViewById(rootView, id);
      if (referenceLabel == null) {
        break missingId;
      }

      return new GroupFindReferencesInPageBinding((LinearLayout) rootView, findInPageContainer,
          findInPageNext, findInPagePrev, referenceCount, referenceLabel);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
