// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import org.wikipedia.R;
import org.wikipedia.onboarding.OnboardingPageView;

public final class InflateDescriptionEditTutorialPageThreeBinding implements ViewBinding {
  @NonNull
  private final OnboardingPageView rootView;

  private InflateDescriptionEditTutorialPageThreeBinding(@NonNull OnboardingPageView rootView) {
    this.rootView = rootView;
  }

  @Override
  @NonNull
  public OnboardingPageView getRoot() {
    return rootView;
  }

  @NonNull
  public static InflateDescriptionEditTutorialPageThreeBinding inflate(
      @NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static InflateDescriptionEditTutorialPageThreeBinding inflate(
      @NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.inflate_description_edit_tutorial_page_three, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static InflateDescriptionEditTutorialPageThreeBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    return new InflateDescriptionEditTutorialPageThreeBinding((OnboardingPageView) rootView);
  }
}
