// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class InflateLoginAndAccountCreationFooterBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView forgotPasswordLink;

  @NonNull
  public final TextView privacyPolicyLink;

  @NonNull
  public final FrameLayout tempAccountInfoContainer;

  @NonNull
  public final TextView tempAccountInfoText;

  private InflateLoginAndAccountCreationFooterBinding(@NonNull LinearLayout rootView,
      @NonNull TextView forgotPasswordLink, @NonNull TextView privacyPolicyLink,
      @NonNull FrameLayout tempAccountInfoContainer, @NonNull TextView tempAccountInfoText) {
    this.rootView = rootView;
    this.forgotPasswordLink = forgotPasswordLink;
    this.privacyPolicyLink = privacyPolicyLink;
    this.tempAccountInfoContainer = tempAccountInfoContainer;
    this.tempAccountInfoText = tempAccountInfoText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static InflateLoginAndAccountCreationFooterBinding inflate(
      @NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static InflateLoginAndAccountCreationFooterBinding inflate(
      @NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.inflate_login_and_account_creation_footer, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static InflateLoginAndAccountCreationFooterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.forgot_password_link;
      TextView forgotPasswordLink = ViewBindings.findChildViewById(rootView, id);
      if (forgotPasswordLink == null) {
        break missingId;
      }

      id = R.id.privacy_policy_link;
      TextView privacyPolicyLink = ViewBindings.findChildViewById(rootView, id);
      if (privacyPolicyLink == null) {
        break missingId;
      }

      id = R.id.temp_account_info_container;
      FrameLayout tempAccountInfoContainer = ViewBindings.findChildViewById(rootView, id);
      if (tempAccountInfoContainer == null) {
        break missingId;
      }

      id = R.id.temp_account_info_text;
      TextView tempAccountInfoText = ViewBindings.findChildViewById(rootView, id);
      if (tempAccountInfoText == null) {
        break missingId;
      }

      return new InflateLoginAndAccountCreationFooterBinding((LinearLayout) rootView,
          forgotPasswordLink, privacyPolicyLink, tempAccountInfoContainer, tempAccountInfoText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
