// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class InflateEditAccountFooterBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final FrameLayout tempAccountInfoContainer;

  @NonNull
  public final ImageView tempAccountInfoIcon;

  @NonNull
  public final TextView tempAccountInfoText;

  private InflateEditAccountFooterBinding(@NonNull FrameLayout rootView,
      @NonNull FrameLayout tempAccountInfoContainer, @NonNull ImageView tempAccountInfoIcon,
      @NonNull TextView tempAccountInfoText) {
    this.rootView = rootView;
    this.tempAccountInfoContainer = tempAccountInfoContainer;
    this.tempAccountInfoIcon = tempAccountInfoIcon;
    this.tempAccountInfoText = tempAccountInfoText;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static InflateEditAccountFooterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static InflateEditAccountFooterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.inflate_edit_account_footer, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static InflateEditAccountFooterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      FrameLayout tempAccountInfoContainer = (FrameLayout) rootView;

      id = R.id.temp_account_info_icon;
      ImageView tempAccountInfoIcon = ViewBindings.findChildViewById(rootView, id);
      if (tempAccountInfoIcon == null) {
        break missingId;
      }

      id = R.id.temp_account_info_text;
      TextView tempAccountInfoText = ViewBindings.findChildViewById(rootView, id);
      if (tempAccountInfoText == null) {
        break missingId;
      }

      return new InflateEditAccountFooterBinding((FrameLayout) rootView, tempAccountInfoContainer,
          tempAccountInfoIcon, tempAccountInfoText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
