// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import org.wikipedia.R;

public final class ItemSuggestedEditsRecentEditsDateBinding implements ViewBinding {
  @NonNull
  private final TextView rootView;

  @NonNull
  public final TextView dateText;

  private ItemSuggestedEditsRecentEditsDateBinding(@NonNull TextView rootView,
      @NonNull TextView dateText) {
    this.rootView = rootView;
    this.dateText = dateText;
  }

  @Override
  @NonNull
  public TextView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemSuggestedEditsRecentEditsDateBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemSuggestedEditsRecentEditsDateBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_suggested_edits_recent_edits_date, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemSuggestedEditsRecentEditsDateBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    TextView dateText = (TextView) rootView;

    return new ItemSuggestedEditsRecentEditsDateBinding((TextView) rootView, dateText);
  }
}
