// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.LangCodeView;

public final class ItemSearchNoResultsBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final LangCodeView languageCode;

  @NonNull
  public final TextView resultsText;

  private ItemSearchNoResultsBinding(@NonNull ConstraintLayout rootView,
      @NonNull LangCodeView languageCode, @NonNull TextView resultsText) {
    this.rootView = rootView;
    this.languageCode = languageCode;
    this.resultsText = resultsText;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemSearchNoResultsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemSearchNoResultsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_search_no_results, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemSearchNoResultsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.language_code;
      LangCodeView languageCode = ViewBindings.findChildViewById(rootView, id);
      if (languageCode == null) {
        break missingId;
      }

      id = R.id.results_text;
      TextView resultsText = ViewBindings.findChildViewById(rootView, id);
      if (resultsText == null) {
        break missingId;
      }

      return new ItemSearchNoResultsBinding((ConstraintLayout) rootView, languageCode, resultsText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
