// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiCardView;

public final class ItemTabContentsBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final TextView tabArticleDescription;

  @NonNull
  public final TextView tabArticleTitle;

  @NonNull
  public final WikiCardView tabCardView;

  @NonNull
  public final ImageView tabCloseButton;

  @NonNull
  public final ConstraintLayout tabContainer;

  private ItemTabContentsBinding(@NonNull FrameLayout rootView,
      @NonNull TextView tabArticleDescription, @NonNull TextView tabArticleTitle,
      @NonNull WikiCardView tabCardView, @NonNull ImageView tabCloseButton,
      @NonNull ConstraintLayout tabContainer) {
    this.rootView = rootView;
    this.tabArticleDescription = tabArticleDescription;
    this.tabArticleTitle = tabArticleTitle;
    this.tabCardView = tabCardView;
    this.tabCloseButton = tabCloseButton;
    this.tabContainer = tabContainer;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemTabContentsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemTabContentsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_tab_contents, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemTabContentsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.tabArticleDescription;
      TextView tabArticleDescription = ViewBindings.findChildViewById(rootView, id);
      if (tabArticleDescription == null) {
        break missingId;
      }

      id = R.id.tabArticleTitle;
      TextView tabArticleTitle = ViewBindings.findChildViewById(rootView, id);
      if (tabArticleTitle == null) {
        break missingId;
      }

      id = R.id.tabCardView;
      WikiCardView tabCardView = ViewBindings.findChildViewById(rootView, id);
      if (tabCardView == null) {
        break missingId;
      }

      id = R.id.tabCloseButton;
      ImageView tabCloseButton = ViewBindings.findChildViewById(rootView, id);
      if (tabCloseButton == null) {
        break missingId;
      }

      id = R.id.tabContainer;
      ConstraintLayout tabContainer = ViewBindings.findChildViewById(rootView, id);
      if (tabContainer == null) {
        break missingId;
      }

      return new ItemTabContentsBinding((FrameLayout) rootView, tabArticleDescription,
          tabArticleTitle, tabCardView, tabCloseButton, tabContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
