// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import org.wikipedia.R;

public final class ItemCustomizeToolbarSetToDefaultBinding implements ViewBinding {
  @NonNull
  private final TextView rootView;

  @NonNull
  public final TextView resetToDefaultButton;

  private ItemCustomizeToolbarSetToDefaultBinding(@NonNull TextView rootView,
      @NonNull TextView resetToDefaultButton) {
    this.rootView = rootView;
    this.resetToDefaultButton = resetToDefaultButton;
  }

  @Override
  @NonNull
  public TextView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemCustomizeToolbarSetToDefaultBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemCustomizeToolbarSetToDefaultBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_customize_toolbar_set_to_default, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemCustomizeToolbarSetToDefaultBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    TextView resetToDefaultButton = (TextView) rootView;

    return new ItemCustomizeToolbarSetToDefaultBinding((TextView) rootView, resetToDefaultButton);
  }
}
