// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ItemTocEntryBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView pageTocItemBullet;

  @NonNull
  public final TextView pageTocItemText;

  private ItemTocEntryBinding(@NonNull LinearLayout rootView, @NonNull ImageView pageTocItemBullet,
      @NonNull TextView pageTocItemText) {
    this.rootView = rootView;
    this.pageTocItemBullet = pageTocItemBullet;
    this.pageTocItemText = pageTocItemText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemTocEntryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemTocEntryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_toc_entry, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemTocEntryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.page_toc_item_bullet;
      ImageView pageTocItemBullet = ViewBindings.findChildViewById(rootView, id);
      if (pageTocItemBullet == null) {
        break missingId;
      }

      id = R.id.page_toc_item_text;
      TextView pageTocItemText = ViewBindings.findChildViewById(rootView, id);
      if (pageTocItemText == null) {
        break missingId;
      }

      return new ItemTocEntryBinding((LinearLayout) rootView, pageTocItemBullet, pageTocItemText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
