// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ItemWikidataLabelBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView labelDescription;

  @NonNull
  public final TextView labelName;

  private ItemWikidataLabelBinding(@NonNull LinearLayout rootView,
      @NonNull TextView labelDescription, @NonNull TextView labelName) {
    this.rootView = rootView;
    this.labelDescription = labelDescription;
    this.labelName = labelName;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemWikidataLabelBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemWikidataLabelBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_wikidata_label, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemWikidataLabelBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.labelDescription;
      TextView labelDescription = ViewBindings.findChildViewById(rootView, id);
      if (labelDescription == null) {
        break missingId;
      }

      id = R.id.labelName;
      TextView labelName = ViewBindings.findChildViewById(rootView, id);
      if (labelName == null) {
        break missingId;
      }

      return new ItemWikidataLabelBinding((LinearLayout) rootView, labelDescription, labelName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
