// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ItemLanguageListEntryBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView languageSubtitle;

  @NonNull
  public final TextView localizedLanguageName;

  private ItemLanguageListEntryBinding(@NonNull LinearLayout rootView,
      @NonNull TextView languageSubtitle, @NonNull TextView localizedLanguageName) {
    this.rootView = rootView;
    this.languageSubtitle = languageSubtitle;
    this.localizedLanguageName = localizedLanguageName;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemLanguageListEntryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemLanguageListEntryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_language_list_entry, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemLanguageListEntryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.language_subtitle;
      TextView languageSubtitle = ViewBindings.findChildViewById(rootView, id);
      if (languageSubtitle == null) {
        break missingId;
      }

      id = R.id.localized_language_name;
      TextView localizedLanguageName = ViewBindings.findChildViewById(rootView, id);
      if (localizedLanguageName == null) {
        break missingId;
      }

      return new ItemLanguageListEntryBinding((LinearLayout) rootView, languageSubtitle,
          localizedLanguageName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
