// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import org.wikipedia.R;

public final class ItemNamespaceBinding implements ViewBinding {
  @NonNull
  private final TextView rootView;

  @NonNull
  public final TextView namespaceText;

  private ItemNamespaceBinding(@NonNull TextView rootView, @NonNull TextView namespaceText) {
    this.rootView = rootView;
    this.namespaceText = namespaceText;
  }

  @Override
  @NonNull
  public TextView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemNamespaceBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemNamespaceBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_namespace, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemNamespaceBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    TextView namespaceText = (TextView) rootView;

    return new ItemNamespaceBinding((TextView) rootView, namespaceText);
  }
}
