// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.LangCodeView;

public final class ItemNotificationFilterBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ImageView notificationFilterCheck;

  @NonNull
  public final LangCodeView notificationFilterLanguageCode;

  @NonNull
  public final TextView notificationFilterTitle;

  @NonNull
  public final ImageView notificationFilterWikiLogo;

  private ItemNotificationFilterBinding(@NonNull View rootView,
      @NonNull ImageView notificationFilterCheck,
      @NonNull LangCodeView notificationFilterLanguageCode,
      @NonNull TextView notificationFilterTitle, @NonNull ImageView notificationFilterWikiLogo) {
    this.rootView = rootView;
    this.notificationFilterCheck = notificationFilterCheck;
    this.notificationFilterLanguageCode = notificationFilterLanguageCode;
    this.notificationFilterTitle = notificationFilterTitle;
    this.notificationFilterWikiLogo = notificationFilterWikiLogo;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemNotificationFilterBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.item_notification_filter, parent);
    return bind(parent);
  }

  @NonNull
  public static ItemNotificationFilterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.notification_filter_check;
      ImageView notificationFilterCheck = ViewBindings.findChildViewById(rootView, id);
      if (notificationFilterCheck == null) {
        break missingId;
      }

      id = R.id.notification_filter_language_code;
      LangCodeView notificationFilterLanguageCode = ViewBindings.findChildViewById(rootView, id);
      if (notificationFilterLanguageCode == null) {
        break missingId;
      }

      id = R.id.notification_filter_title;
      TextView notificationFilterTitle = ViewBindings.findChildViewById(rootView, id);
      if (notificationFilterTitle == null) {
        break missingId;
      }

      id = R.id.notification_filter_wiki_logo;
      ImageView notificationFilterWikiLogo = ViewBindings.findChildViewById(rootView, id);
      if (notificationFilterWikiLogo == null) {
        break missingId;
      }

      return new ItemNotificationFilterBinding(rootView, notificationFilterCheck,
          notificationFilterLanguageCode, notificationFilterTitle, notificationFilterWikiLogo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
