// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiCardView;

public final class ItemEditHistoryBinding implements ViewBinding {
  @NonNull
  private final WikiCardView rootView;

  @NonNull
  public final WikiCardView cardView;

  @NonNull
  public final ConstraintLayout clickTargetView;

  @NonNull
  public final TextView diffText;

  @NonNull
  public final TextView editHistoryTimeText;

  @NonNull
  public final TextView editHistoryTitle;

  @NonNull
  public final ImageView selectButton;

  @NonNull
  public final Flow userNameAndDiffFlow;

  @NonNull
  public final MaterialButton userNameText;

  private ItemEditHistoryBinding(@NonNull WikiCardView rootView, @NonNull WikiCardView cardView,
      @NonNull ConstraintLayout clickTargetView, @NonNull TextView diffText,
      @NonNull TextView editHistoryTimeText, @NonNull TextView editHistoryTitle,
      @NonNull ImageView selectButton, @NonNull Flow userNameAndDiffFlow,
      @NonNull MaterialButton userNameText) {
    this.rootView = rootView;
    this.cardView = cardView;
    this.clickTargetView = clickTargetView;
    this.diffText = diffText;
    this.editHistoryTimeText = editHistoryTimeText;
    this.editHistoryTitle = editHistoryTitle;
    this.selectButton = selectButton;
    this.userNameAndDiffFlow = userNameAndDiffFlow;
    this.userNameText = userNameText;
  }

  @Override
  @NonNull
  public WikiCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemEditHistoryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemEditHistoryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_edit_history, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemEditHistoryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      WikiCardView cardView = (WikiCardView) rootView;

      id = R.id.clickTargetView;
      ConstraintLayout clickTargetView = ViewBindings.findChildViewById(rootView, id);
      if (clickTargetView == null) {
        break missingId;
      }

      id = R.id.diffText;
      TextView diffText = ViewBindings.findChildViewById(rootView, id);
      if (diffText == null) {
        break missingId;
      }

      id = R.id.editHistoryTimeText;
      TextView editHistoryTimeText = ViewBindings.findChildViewById(rootView, id);
      if (editHistoryTimeText == null) {
        break missingId;
      }

      id = R.id.editHistoryTitle;
      TextView editHistoryTitle = ViewBindings.findChildViewById(rootView, id);
      if (editHistoryTitle == null) {
        break missingId;
      }

      id = R.id.selectButton;
      ImageView selectButton = ViewBindings.findChildViewById(rootView, id);
      if (selectButton == null) {
        break missingId;
      }

      id = R.id.userNameAndDiffFlow;
      Flow userNameAndDiffFlow = ViewBindings.findChildViewById(rootView, id);
      if (userNameAndDiffFlow == null) {
        break missingId;
      }

      id = R.id.userNameText;
      MaterialButton userNameText = ViewBindings.findChildViewById(rootView, id);
      if (userNameText == null) {
        break missingId;
      }

      return new ItemEditHistoryBinding((WikiCardView) rootView, cardView, clickTargetView,
          diffText, editHistoryTimeText, editHistoryTitle, selectButton, userNameAndDiffFlow,
          userNameText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
