// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ItemFeedContentTypeLangSelectItemBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final CheckBox feedContentTypeLangCheckbox;

  @NonNull
  public final LinearLayout feedContentTypeLangContainer;

  @NonNull
  public final TextView feedContentTypeLangName;

  private ItemFeedContentTypeLangSelectItemBinding(@NonNull LinearLayout rootView,
      @NonNull CheckBox feedContentTypeLangCheckbox,
      @NonNull LinearLayout feedContentTypeLangContainer,
      @NonNull TextView feedContentTypeLangName) {
    this.rootView = rootView;
    this.feedContentTypeLangCheckbox = feedContentTypeLangCheckbox;
    this.feedContentTypeLangContainer = feedContentTypeLangContainer;
    this.feedContentTypeLangName = feedContentTypeLangName;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemFeedContentTypeLangSelectItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemFeedContentTypeLangSelectItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_feed_content_type_lang_select_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemFeedContentTypeLangSelectItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.feed_content_type_lang_checkbox;
      CheckBox feedContentTypeLangCheckbox = ViewBindings.findChildViewById(rootView, id);
      if (feedContentTypeLangCheckbox == null) {
        break missingId;
      }

      LinearLayout feedContentTypeLangContainer = (LinearLayout) rootView;

      id = R.id.feed_content_type_lang_name;
      TextView feedContentTypeLangName = ViewBindings.findChildViewById(rootView, id);
      if (feedContentTypeLangName == null) {
        break missingId;
      }

      return new ItemFeedContentTypeLangSelectItemBinding((LinearLayout) rootView,
          feedContentTypeLangCheckbox, feedContentTypeLangContainer, feedContentTypeLangName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
