// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import java.lang.NullPointerException;
import java.lang.Override;
import org.wikipedia.R;

public final class PreferenceMultilineWithSystemActionBinding implements ViewBinding {
  @NonNull
  private final ImageView rootView;

  @NonNull
  public final ImageView rightIcon;

  private PreferenceMultilineWithSystemActionBinding(@NonNull ImageView rootView,
      @NonNull ImageView rightIcon) {
    this.rootView = rootView;
    this.rightIcon = rightIcon;
  }

  @Override
  @NonNull
  public ImageView getRoot() {
    return rootView;
  }

  @NonNull
  public static PreferenceMultilineWithSystemActionBinding inflate(
      @NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static PreferenceMultilineWithSystemActionBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.preference_multiline_with_system_action, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static PreferenceMultilineWithSystemActionBinding bind(@NonNull View rootView) {
    if (rootView == null) {
      throw new NullPointerException("rootView");
    }

    ImageView rightIcon = (ImageView) rootView;

    return new PreferenceMultilineWithSystemActionBinding((ImageView) rootView, rightIcon);
  }
}
