// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.SuggestedEditsStatsView;
import org.wikipedia.views.WikiCardView;

public final class SuggestedEditsTasksContributionContainerBinding implements ViewBinding {
  @NonNull
  private final WikiCardView rootView;

  @NonNull
  public final LinearLayout contributionsContainer;

  @NonNull
  public final SuggestedEditsStatsView editQualityStatsView;

  @NonNull
  public final SuggestedEditsStatsView editStreakStatsView;

  @NonNull
  public final SuggestedEditsStatsView editsCountStatsView;

  @NonNull
  public final SuggestedEditsStatsView pageViewStatsView;

  @NonNull
  public final View statsDivider;

  private SuggestedEditsTasksContributionContainerBinding(@NonNull WikiCardView rootView,
      @NonNull LinearLayout contributionsContainer,
      @NonNull SuggestedEditsStatsView editQualityStatsView,
      @NonNull SuggestedEditsStatsView editStreakStatsView,
      @NonNull SuggestedEditsStatsView editsCountStatsView,
      @NonNull SuggestedEditsStatsView pageViewStatsView, @NonNull View statsDivider) {
    this.rootView = rootView;
    this.contributionsContainer = contributionsContainer;
    this.editQualityStatsView = editQualityStatsView;
    this.editStreakStatsView = editStreakStatsView;
    this.editsCountStatsView = editsCountStatsView;
    this.pageViewStatsView = pageViewStatsView;
    this.statsDivider = statsDivider;
  }

  @Override
  @NonNull
  public WikiCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static SuggestedEditsTasksContributionContainerBinding inflate(
      @NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SuggestedEditsTasksContributionContainerBinding inflate(
      @NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.suggested_edits_tasks_contribution_container, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SuggestedEditsTasksContributionContainerBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.contributionsContainer;
      LinearLayout contributionsContainer = ViewBindings.findChildViewById(rootView, id);
      if (contributionsContainer == null) {
        break missingId;
      }

      id = R.id.editQualityStatsView;
      SuggestedEditsStatsView editQualityStatsView = ViewBindings.findChildViewById(rootView, id);
      if (editQualityStatsView == null) {
        break missingId;
      }

      id = R.id.editStreakStatsView;
      SuggestedEditsStatsView editStreakStatsView = ViewBindings.findChildViewById(rootView, id);
      if (editStreakStatsView == null) {
        break missingId;
      }

      id = R.id.editsCountStatsView;
      SuggestedEditsStatsView editsCountStatsView = ViewBindings.findChildViewById(rootView, id);
      if (editsCountStatsView == null) {
        break missingId;
      }

      id = R.id.pageViewStatsView;
      SuggestedEditsStatsView pageViewStatsView = ViewBindings.findChildViewById(rootView, id);
      if (pageViewStatsView == null) {
        break missingId;
      }

      id = R.id.statsDivider;
      View statsDivider = ViewBindings.findChildViewById(rootView, id);
      if (statsDivider == null) {
        break missingId;
      }

      return new SuggestedEditsTasksContributionContainerBinding((WikiCardView) rootView,
          contributionsContainer, editQualityStatsView, editStreakStatsView, editsCountStatsView,
          pageViewStatsView, statsDivider);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
