// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewWikitextKeyboardHeadingsBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ImageView closeButton;

  @NonNull
  public final ImageView wikitextButtonH2;

  @NonNull
  public final ImageView wikitextButtonH3;

  @NonNull
  public final ImageView wikitextButtonH4;

  @NonNull
  public final ImageView wikitextButtonH5;

  private ViewWikitextKeyboardHeadingsBinding(@NonNull View rootView,
      @NonNull ImageView closeButton, @NonNull ImageView wikitextButtonH2,
      @NonNull ImageView wikitextButtonH3, @NonNull ImageView wikitextButtonH4,
      @NonNull ImageView wikitextButtonH5) {
    this.rootView = rootView;
    this.closeButton = closeButton;
    this.wikitextButtonH2 = wikitextButtonH2;
    this.wikitextButtonH3 = wikitextButtonH3;
    this.wikitextButtonH4 = wikitextButtonH4;
    this.wikitextButtonH5 = wikitextButtonH5;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewWikitextKeyboardHeadingsBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_wikitext_keyboard_headings, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewWikitextKeyboardHeadingsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.closeButton;
      ImageView closeButton = ViewBindings.findChildViewById(rootView, id);
      if (closeButton == null) {
        break missingId;
      }

      id = R.id.wikitext_button_h2;
      ImageView wikitextButtonH2 = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonH2 == null) {
        break missingId;
      }

      id = R.id.wikitext_button_h3;
      ImageView wikitextButtonH3 = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonH3 == null) {
        break missingId;
      }

      id = R.id.wikitext_button_h4;
      ImageView wikitextButtonH4 = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonH4 == null) {
        break missingId;
      }

      id = R.id.wikitext_button_h5;
      ImageView wikitextButtonH5 = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonH5 == null) {
        break missingId;
      }

      return new ViewWikitextKeyboardHeadingsBinding(rootView, closeButton, wikitextButtonH2,
          wikitextButtonH3, wikitextButtonH4, wikitextButtonH5);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
