// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Space;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewWikiErrorBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final Space viewWikiErrorArticleContentTopOffset;

  @NonNull
  public final Space viewWikiErrorArticleTabLayoutOffset;

  @NonNull
  public final Button viewWikiErrorButton;

  @NonNull
  public final LinearLayout viewWikiErrorFooterLayout;

  @NonNull
  public final TextView viewWikiErrorFooterText;

  @NonNull
  public final ImageView viewWikiErrorIcon;

  @NonNull
  public final TextView viewWikiErrorText;

  private ViewWikiErrorBinding(@NonNull View rootView,
      @NonNull Space viewWikiErrorArticleContentTopOffset,
      @NonNull Space viewWikiErrorArticleTabLayoutOffset, @NonNull Button viewWikiErrorButton,
      @NonNull LinearLayout viewWikiErrorFooterLayout, @NonNull TextView viewWikiErrorFooterText,
      @NonNull ImageView viewWikiErrorIcon, @NonNull TextView viewWikiErrorText) {
    this.rootView = rootView;
    this.viewWikiErrorArticleContentTopOffset = viewWikiErrorArticleContentTopOffset;
    this.viewWikiErrorArticleTabLayoutOffset = viewWikiErrorArticleTabLayoutOffset;
    this.viewWikiErrorButton = viewWikiErrorButton;
    this.viewWikiErrorFooterLayout = viewWikiErrorFooterLayout;
    this.viewWikiErrorFooterText = viewWikiErrorFooterText;
    this.viewWikiErrorIcon = viewWikiErrorIcon;
    this.viewWikiErrorText = viewWikiErrorText;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewWikiErrorBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_wiki_error, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewWikiErrorBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.view_wiki_error_article_content_top_offset;
      Space viewWikiErrorArticleContentTopOffset = ViewBindings.findChildViewById(rootView, id);
      if (viewWikiErrorArticleContentTopOffset == null) {
        break missingId;
      }

      id = R.id.view_wiki_error_article_tab_layout_offset;
      Space viewWikiErrorArticleTabLayoutOffset = ViewBindings.findChildViewById(rootView, id);
      if (viewWikiErrorArticleTabLayoutOffset == null) {
        break missingId;
      }

      id = R.id.view_wiki_error_button;
      Button viewWikiErrorButton = ViewBindings.findChildViewById(rootView, id);
      if (viewWikiErrorButton == null) {
        break missingId;
      }

      id = R.id.view_wiki_error_footer_layout;
      LinearLayout viewWikiErrorFooterLayout = ViewBindings.findChildViewById(rootView, id);
      if (viewWikiErrorFooterLayout == null) {
        break missingId;
      }

      id = R.id.view_wiki_error_footer_text;
      TextView viewWikiErrorFooterText = ViewBindings.findChildViewById(rootView, id);
      if (viewWikiErrorFooterText == null) {
        break missingId;
      }

      id = R.id.view_wiki_error_icon;
      ImageView viewWikiErrorIcon = ViewBindings.findChildViewById(rootView, id);
      if (viewWikiErrorIcon == null) {
        break missingId;
      }

      id = R.id.view_wiki_error_text;
      TextView viewWikiErrorText = ViewBindings.findChildViewById(rootView, id);
      if (viewWikiErrorText == null) {
        break missingId;
      }

      return new ViewWikiErrorBinding(rootView, viewWikiErrorArticleContentTopOffset,
          viewWikiErrorArticleTabLayoutOffset, viewWikiErrorButton, viewWikiErrorFooterLayout,
          viewWikiErrorFooterText, viewWikiErrorIcon, viewWikiErrorText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
