// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.UserMentionEditText;

public final class ViewUserMentionInputBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final UserMentionEditText inputEditText;

  @NonNull
  public final TextInputLayout inputTextLayout;

  @NonNull
  public final RecyclerView userListRecycler;

  private ViewUserMentionInputBinding(@NonNull View rootView,
      @NonNull UserMentionEditText inputEditText, @NonNull TextInputLayout inputTextLayout,
      @NonNull RecyclerView userListRecycler) {
    this.rootView = rootView;
    this.inputEditText = inputEditText;
    this.inputTextLayout = inputTextLayout;
    this.userListRecycler = userListRecycler;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewUserMentionInputBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_user_mention_input, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewUserMentionInputBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.inputEditText;
      UserMentionEditText inputEditText = ViewBindings.findChildViewById(rootView, id);
      if (inputEditText == null) {
        break missingId;
      }

      id = R.id.inputTextLayout;
      TextInputLayout inputTextLayout = ViewBindings.findChildViewById(rootView, id);
      if (inputTextLayout == null) {
        break missingId;
      }

      id = R.id.userListRecycler;
      RecyclerView userListRecycler = ViewBindings.findChildViewById(rootView, id);
      if (userListRecycler == null) {
        break missingId;
      }

      return new ViewUserMentionInputBinding(rootView, inputEditText, inputTextLayout,
          userListRecycler);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
