// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.CabSearchView;

public final class ViewSearchAndFilterBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView filterCount;

  @NonNull
  public final ImageView filterIcon;

  @NonNull
  public final CabSearchView searchInput;

  private ViewSearchAndFilterBinding(@NonNull LinearLayout rootView, @NonNull TextView filterCount,
      @NonNull ImageView filterIcon, @NonNull CabSearchView searchInput) {
    this.rootView = rootView;
    this.filterCount = filterCount;
    this.filterIcon = filterIcon;
    this.searchInput = searchInput;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewSearchAndFilterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewSearchAndFilterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_search_and_filter, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewSearchAndFilterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.filter_count;
      TextView filterCount = ViewBindings.findChildViewById(rootView, id);
      if (filterCount == null) {
        break missingId;
      }

      id = R.id.filter_icon;
      ImageView filterIcon = ViewBindings.findChildViewById(rootView, id);
      if (filterIcon == null) {
        break missingId;
      }

      id = R.id.search_input;
      CabSearchView searchInput = ViewBindings.findChildViewById(rootView, id);
      if (searchInput == null) {
        break missingId;
      }

      return new ViewSearchAndFilterBinding((LinearLayout) rootView, filterCount, filterIcon,
          searchInput);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
