// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.ImageDetailView;

public final class ViewFilePageBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final LinearLayout detailsContainer;

  @NonNull
  public final ImageDetailView filenameView;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final FrameLayout imageViewPlaceholder;

  private ViewFilePageBinding(@NonNull View rootView, @NonNull LinearLayout detailsContainer,
      @NonNull ImageDetailView filenameView, @NonNull ImageView imageView,
      @NonNull FrameLayout imageViewPlaceholder) {
    this.rootView = rootView;
    this.detailsContainer = detailsContainer;
    this.filenameView = filenameView;
    this.imageView = imageView;
    this.imageViewPlaceholder = imageViewPlaceholder;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewFilePageBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_file_page, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewFilePageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.detailsContainer;
      LinearLayout detailsContainer = ViewBindings.findChildViewById(rootView, id);
      if (detailsContainer == null) {
        break missingId;
      }

      id = R.id.filenameView;
      ImageDetailView filenameView = ViewBindings.findChildViewById(rootView, id);
      if (filenameView == null) {
        break missingId;
      }

      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      id = R.id.imageViewPlaceholder;
      FrameLayout imageViewPlaceholder = ViewBindings.findChildViewById(rootView, id);
      if (imageViewPlaceholder == null) {
        break missingId;
      }

      return new ViewFilePageBinding(rootView, detailsContainer, filenameView, imageView,
          imageViewPlaceholder);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
