// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewOnboardingLanguageListBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button addLanguageButton;

  @NonNull
  public final RecyclerView languagesList;

  private ViewOnboardingLanguageListBinding(@NonNull LinearLayout rootView,
      @NonNull Button addLanguageButton, @NonNull RecyclerView languagesList) {
    this.rootView = rootView;
    this.addLanguageButton = addLanguageButton;
    this.languagesList = languagesList;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewOnboardingLanguageListBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewOnboardingLanguageListBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_onboarding_language_list, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewOnboardingLanguageListBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.addLanguageButton;
      Button addLanguageButton = ViewBindings.findChildViewById(rootView, id);
      if (addLanguageButton == null) {
        break missingId;
      }

      id = R.id.languagesList;
      RecyclerView languagesList = ViewBindings.findChildViewById(rootView, id);
      if (languagesList == null) {
        break missingId;
      }

      return new ViewOnboardingLanguageListBinding((LinearLayout) rootView, addLanguageButton,
          languagesList);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
