// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.feed.view.CardHeaderView;

public final class ViewCardNewsBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final CardHeaderView headerView;

  @NonNull
  public final RecyclerView newsCardviewRecyclerView;

  @NonNull
  public final LinearLayout rtlContainer;

  private ViewCardNewsBinding(@NonNull LinearLayout rootView, @NonNull CardHeaderView headerView,
      @NonNull RecyclerView newsCardviewRecyclerView, @NonNull LinearLayout rtlContainer) {
    this.rootView = rootView;
    this.headerView = headerView;
    this.newsCardviewRecyclerView = newsCardviewRecyclerView;
    this.rtlContainer = rtlContainer;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewCardNewsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewCardNewsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_card_news, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewCardNewsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.header_view;
      CardHeaderView headerView = ViewBindings.findChildViewById(rootView, id);
      if (headerView == null) {
        break missingId;
      }

      id = R.id.news_cardview_recycler_view;
      RecyclerView newsCardviewRecyclerView = ViewBindings.findChildViewById(rootView, id);
      if (newsCardviewRecyclerView == null) {
        break missingId;
      }

      LinearLayout rtlContainer = (LinearLayout) rootView;

      return new ViewCardNewsBinding((LinearLayout) rootView, headerView, newsCardviewRecyclerView,
          rtlContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
