// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.feed.view.CardFooterView;
import org.wikipedia.feed.view.CardHeaderView;
import org.wikipedia.views.WikiArticleCardView;
import org.wikipedia.views.WikiCardView;

public final class ViewCardFeaturedArticleBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final WikiCardView viewFeaturedArticleCardContentContainer;

  @NonNull
  public final CardFooterView viewFeaturedArticleCardFooter;

  @NonNull
  public final CardHeaderView viewFeaturedArticleCardHeader;

  @NonNull
  public final WikiArticleCardView viewWikiArticleCard;

  private ViewCardFeaturedArticleBinding(@NonNull ConstraintLayout rootView,
      @NonNull WikiCardView viewFeaturedArticleCardContentContainer,
      @NonNull CardFooterView viewFeaturedArticleCardFooter,
      @NonNull CardHeaderView viewFeaturedArticleCardHeader,
      @NonNull WikiArticleCardView viewWikiArticleCard) {
    this.rootView = rootView;
    this.viewFeaturedArticleCardContentContainer = viewFeaturedArticleCardContentContainer;
    this.viewFeaturedArticleCardFooter = viewFeaturedArticleCardFooter;
    this.viewFeaturedArticleCardHeader = viewFeaturedArticleCardHeader;
    this.viewWikiArticleCard = viewWikiArticleCard;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewCardFeaturedArticleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewCardFeaturedArticleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_card_featured_article, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewCardFeaturedArticleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.view_featured_article_card_content_container;
      WikiCardView viewFeaturedArticleCardContentContainer = ViewBindings.findChildViewById(rootView, id);
      if (viewFeaturedArticleCardContentContainer == null) {
        break missingId;
      }

      id = R.id.view_featured_article_card_footer;
      CardFooterView viewFeaturedArticleCardFooter = ViewBindings.findChildViewById(rootView, id);
      if (viewFeaturedArticleCardFooter == null) {
        break missingId;
      }

      id = R.id.view_featured_article_card_header;
      CardHeaderView viewFeaturedArticleCardHeader = ViewBindings.findChildViewById(rootView, id);
      if (viewFeaturedArticleCardHeader == null) {
        break missingId;
      }

      id = R.id.view_wiki_article_card;
      WikiArticleCardView viewWikiArticleCard = ViewBindings.findChildViewById(rootView, id);
      if (viewWikiArticleCard == null) {
        break missingId;
      }

      return new ViewCardFeaturedArticleBinding((ConstraintLayout) rootView,
          viewFeaturedArticleCardContentContainer, viewFeaturedArticleCardFooter,
          viewFeaturedArticleCardHeader, viewWikiArticleCard);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
