// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewRecommendedContentSectionBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView sectionHeader;

  @NonNull
  public final RecyclerView sectionList;

  private ViewRecommendedContentSectionBinding(@NonNull LinearLayout rootView,
      @NonNull TextView sectionHeader, @NonNull RecyclerView sectionList) {
    this.rootView = rootView;
    this.sectionHeader = sectionHeader;
    this.sectionList = sectionList;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewRecommendedContentSectionBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewRecommendedContentSectionBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_recommended_content_section, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewRecommendedContentSectionBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.sectionHeader;
      TextView sectionHeader = ViewBindings.findChildViewById(rootView, id);
      if (sectionHeader == null) {
        break missingId;
      }

      id = R.id.sectionList;
      RecyclerView sectionList = ViewBindings.findChildViewById(rootView, id);
      if (sectionList == null) {
        break missingId;
      }

      return new ViewRecommendedContentSectionBinding((LinearLayout) rootView, sectionHeader,
          sectionList);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
