// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.CircularProgressBar;

public final class ViewSuggestedEditsStatsBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final CircularProgressBar circularProgressBar;

  @NonNull
  public final ImageView circularProgressBarOverlay;

  @NonNull
  public final TextView description;

  @NonNull
  public final ImageView image;

  @NonNull
  public final TextView title;

  private ViewSuggestedEditsStatsBinding(@NonNull View rootView,
      @NonNull CircularProgressBar circularProgressBar,
      @NonNull ImageView circularProgressBarOverlay, @NonNull TextView description,
      @NonNull ImageView image, @NonNull TextView title) {
    this.rootView = rootView;
    this.circularProgressBar = circularProgressBar;
    this.circularProgressBarOverlay = circularProgressBarOverlay;
    this.description = description;
    this.image = image;
    this.title = title;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewSuggestedEditsStatsBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_suggested_edits_stats, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewSuggestedEditsStatsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.circularProgressBar;
      CircularProgressBar circularProgressBar = ViewBindings.findChildViewById(rootView, id);
      if (circularProgressBar == null) {
        break missingId;
      }

      id = R.id.circularProgressBarOverlay;
      ImageView circularProgressBarOverlay = ViewBindings.findChildViewById(rootView, id);
      if (circularProgressBarOverlay == null) {
        break missingId;
      }

      id = R.id.description;
      TextView description = ViewBindings.findChildViewById(rootView, id);
      if (description == null) {
        break missingId;
      }

      id = R.id.image;
      ImageView image = ViewBindings.findChildViewById(rootView, id);
      if (image == null) {
        break missingId;
      }

      id = R.id.title;
      TextView title = ViewBindings.findChildViewById(rootView, id);
      if (title == null) {
        break missingId;
      }

      return new ViewSuggestedEditsStatsBinding(rootView, circularProgressBar,
          circularProgressBarOverlay, description, image, title);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
