// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.FaceAndColorDetectImageView;

public final class ViewHorizontalScrollListItemCardBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final FaceAndColorDetectImageView horizontalScrollListItemImage;

  @NonNull
  public final FrameLayout horizontalScrollListItemImageContainer;

  @NonNull
  public final TextView horizontalScrollListItemText;

  private ViewHorizontalScrollListItemCardBinding(@NonNull LinearLayout rootView,
      @NonNull FaceAndColorDetectImageView horizontalScrollListItemImage,
      @NonNull FrameLayout horizontalScrollListItemImageContainer,
      @NonNull TextView horizontalScrollListItemText) {
    this.rootView = rootView;
    this.horizontalScrollListItemImage = horizontalScrollListItemImage;
    this.horizontalScrollListItemImageContainer = horizontalScrollListItemImageContainer;
    this.horizontalScrollListItemText = horizontalScrollListItemText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewHorizontalScrollListItemCardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewHorizontalScrollListItemCardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_horizontal_scroll_list_item_card, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewHorizontalScrollListItemCardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.horizontal_scroll_list_item_image;
      FaceAndColorDetectImageView horizontalScrollListItemImage = ViewBindings.findChildViewById(rootView, id);
      if (horizontalScrollListItemImage == null) {
        break missingId;
      }

      id = R.id.horizontal_scroll_list_item_image_container;
      FrameLayout horizontalScrollListItemImageContainer = ViewBindings.findChildViewById(rootView, id);
      if (horizontalScrollListItemImageContainer == null) {
        break missingId;
      }

      id = R.id.horizontal_scroll_list_item_text;
      TextView horizontalScrollListItemText = ViewBindings.findChildViewById(rootView, id);
      if (horizontalScrollListItemText == null) {
        break missingId;
      }

      return new ViewHorizontalScrollListItemCardBinding((LinearLayout) rootView,
          horizontalScrollListItemImage, horizontalScrollListItemImageContainer,
          horizontalScrollListItemText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
