// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.flexbox.FlexboxLayout;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.FaceAndColorDetectImageView;
import org.wikipedia.views.WikiCardView;

public final class ViewCardAnnouncementBinding implements ViewBinding {
  @NonNull
  private final WikiCardView rootView;

  @NonNull
  public final MaterialButton viewAnnouncementActionNegative;

  @NonNull
  public final MaterialButton viewAnnouncementActionPositive;

  @NonNull
  public final FlexboxLayout viewAnnouncementCardButtonsContainer;

  @NonNull
  public final LinearLayout viewAnnouncementCardDialogButtonsContainer;

  @NonNull
  public final WikiCardView viewAnnouncementContainer;

  @NonNull
  public final MaterialButton viewAnnouncementDialogActionNegative;

  @NonNull
  public final MaterialButton viewAnnouncementDialogActionPositive;

  @NonNull
  public final View viewAnnouncementFooterBorder;

  @NonNull
  public final TextView viewAnnouncementFooterText;

  @NonNull
  public final FaceAndColorDetectImageView viewAnnouncementHeaderImage;

  @NonNull
  public final TextView viewAnnouncementText;

  private ViewCardAnnouncementBinding(@NonNull WikiCardView rootView,
      @NonNull MaterialButton viewAnnouncementActionNegative,
      @NonNull MaterialButton viewAnnouncementActionPositive,
      @NonNull FlexboxLayout viewAnnouncementCardButtonsContainer,
      @NonNull LinearLayout viewAnnouncementCardDialogButtonsContainer,
      @NonNull WikiCardView viewAnnouncementContainer,
      @NonNull MaterialButton viewAnnouncementDialogActionNegative,
      @NonNull MaterialButton viewAnnouncementDialogActionPositive,
      @NonNull View viewAnnouncementFooterBorder, @NonNull TextView viewAnnouncementFooterText,
      @NonNull FaceAndColorDetectImageView viewAnnouncementHeaderImage,
      @NonNull TextView viewAnnouncementText) {
    this.rootView = rootView;
    this.viewAnnouncementActionNegative = viewAnnouncementActionNegative;
    this.viewAnnouncementActionPositive = viewAnnouncementActionPositive;
    this.viewAnnouncementCardButtonsContainer = viewAnnouncementCardButtonsContainer;
    this.viewAnnouncementCardDialogButtonsContainer = viewAnnouncementCardDialogButtonsContainer;
    this.viewAnnouncementContainer = viewAnnouncementContainer;
    this.viewAnnouncementDialogActionNegative = viewAnnouncementDialogActionNegative;
    this.viewAnnouncementDialogActionPositive = viewAnnouncementDialogActionPositive;
    this.viewAnnouncementFooterBorder = viewAnnouncementFooterBorder;
    this.viewAnnouncementFooterText = viewAnnouncementFooterText;
    this.viewAnnouncementHeaderImage = viewAnnouncementHeaderImage;
    this.viewAnnouncementText = viewAnnouncementText;
  }

  @Override
  @NonNull
  public WikiCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewCardAnnouncementBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewCardAnnouncementBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_card_announcement, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewCardAnnouncementBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.view_announcement_action_negative;
      MaterialButton viewAnnouncementActionNegative = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementActionNegative == null) {
        break missingId;
      }

      id = R.id.view_announcement_action_positive;
      MaterialButton viewAnnouncementActionPositive = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementActionPositive == null) {
        break missingId;
      }

      id = R.id.view_announcement_card_buttons_container;
      FlexboxLayout viewAnnouncementCardButtonsContainer = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementCardButtonsContainer == null) {
        break missingId;
      }

      id = R.id.view_announcement_card_dialog_buttons_container;
      LinearLayout viewAnnouncementCardDialogButtonsContainer = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementCardDialogButtonsContainer == null) {
        break missingId;
      }

      WikiCardView viewAnnouncementContainer = (WikiCardView) rootView;

      id = R.id.view_announcement_dialog_action_negative;
      MaterialButton viewAnnouncementDialogActionNegative = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementDialogActionNegative == null) {
        break missingId;
      }

      id = R.id.view_announcement_dialog_action_positive;
      MaterialButton viewAnnouncementDialogActionPositive = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementDialogActionPositive == null) {
        break missingId;
      }

      id = R.id.view_announcement_footer_border;
      View viewAnnouncementFooterBorder = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementFooterBorder == null) {
        break missingId;
      }

      id = R.id.view_announcement_footer_text;
      TextView viewAnnouncementFooterText = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementFooterText == null) {
        break missingId;
      }

      id = R.id.view_announcement_header_image;
      FaceAndColorDetectImageView viewAnnouncementHeaderImage = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementHeaderImage == null) {
        break missingId;
      }

      id = R.id.view_announcement_text;
      TextView viewAnnouncementText = ViewBindings.findChildViewById(rootView, id);
      if (viewAnnouncementText == null) {
        break missingId;
      }

      return new ViewCardAnnouncementBinding((WikiCardView) rootView,
          viewAnnouncementActionNegative, viewAnnouncementActionPositive,
          viewAnnouncementCardButtonsContainer, viewAnnouncementCardDialogButtonsContainer,
          viewAnnouncementContainer, viewAnnouncementDialogActionNegative,
          viewAnnouncementDialogActionPositive, viewAnnouncementFooterBorder,
          viewAnnouncementFooterText, viewAnnouncementHeaderImage, viewAnnouncementText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
