// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewSuggestedEditsTaskItemBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final MaterialButton primaryButton;

  @NonNull
  public final MaterialButton secondaryButton;

  @NonNull
  public final TextView taskDescription;

  @NonNull
  public final ImageView taskIcon;

  @NonNull
  public final TextView taskTitle;

  @NonNull
  public final TextView taskTitleNewLabel;

  private ViewSuggestedEditsTaskItemBinding(@NonNull View rootView,
      @NonNull MaterialButton primaryButton, @NonNull MaterialButton secondaryButton,
      @NonNull TextView taskDescription, @NonNull ImageView taskIcon, @NonNull TextView taskTitle,
      @NonNull TextView taskTitleNewLabel) {
    this.rootView = rootView;
    this.primaryButton = primaryButton;
    this.secondaryButton = secondaryButton;
    this.taskDescription = taskDescription;
    this.taskIcon = taskIcon;
    this.taskTitle = taskTitle;
    this.taskTitleNewLabel = taskTitleNewLabel;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewSuggestedEditsTaskItemBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_suggested_edits_task_item, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewSuggestedEditsTaskItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.primaryButton;
      MaterialButton primaryButton = ViewBindings.findChildViewById(rootView, id);
      if (primaryButton == null) {
        break missingId;
      }

      id = R.id.secondaryButton;
      MaterialButton secondaryButton = ViewBindings.findChildViewById(rootView, id);
      if (secondaryButton == null) {
        break missingId;
      }

      id = R.id.taskDescription;
      TextView taskDescription = ViewBindings.findChildViewById(rootView, id);
      if (taskDescription == null) {
        break missingId;
      }

      id = R.id.taskIcon;
      ImageView taskIcon = ViewBindings.findChildViewById(rootView, id);
      if (taskIcon == null) {
        break missingId;
      }

      id = R.id.taskTitle;
      TextView taskTitle = ViewBindings.findChildViewById(rootView, id);
      if (taskTitle == null) {
        break missingId;
      }

      id = R.id.taskTitleNewLabel;
      TextView taskTitleNewLabel = ViewBindings.findChildViewById(rootView, id);
      if (taskTitleNewLabel == null) {
        break missingId;
      }

      return new ViewSuggestedEditsTaskItemBinding(rootView, primaryButton, secondaryButton,
          taskDescription, taskIcon, taskTitle, taskTitleNewLabel);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
