// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.feed.view.CardFooterView;
import org.wikipedia.feed.view.CardHeaderView;
import org.wikipedia.feed.view.CardLargeHeaderView;
import org.wikipedia.views.WikiCardView;

public final class ViewListCardBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CardFooterView viewListCardFooter;

  @NonNull
  public final CardHeaderView viewListCardHeader;

  @NonNull
  public final CardLargeHeaderView viewListCardLargeHeader;

  @NonNull
  public final WikiCardView viewListCardLargeHeaderContainer;

  @NonNull
  public final RecyclerView viewListCardList;

  @NonNull
  public final WikiCardView viewListCardListContainer;

  private ViewListCardBinding(@NonNull ConstraintLayout rootView,
      @NonNull CardFooterView viewListCardFooter, @NonNull CardHeaderView viewListCardHeader,
      @NonNull CardLargeHeaderView viewListCardLargeHeader,
      @NonNull WikiCardView viewListCardLargeHeaderContainer,
      @NonNull RecyclerView viewListCardList, @NonNull WikiCardView viewListCardListContainer) {
    this.rootView = rootView;
    this.viewListCardFooter = viewListCardFooter;
    this.viewListCardHeader = viewListCardHeader;
    this.viewListCardLargeHeader = viewListCardLargeHeader;
    this.viewListCardLargeHeaderContainer = viewListCardLargeHeaderContainer;
    this.viewListCardList = viewListCardList;
    this.viewListCardListContainer = viewListCardListContainer;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewListCardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewListCardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_list_card, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewListCardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.view_list_card_footer;
      CardFooterView viewListCardFooter = ViewBindings.findChildViewById(rootView, id);
      if (viewListCardFooter == null) {
        break missingId;
      }

      id = R.id.view_list_card_header;
      CardHeaderView viewListCardHeader = ViewBindings.findChildViewById(rootView, id);
      if (viewListCardHeader == null) {
        break missingId;
      }

      id = R.id.view_list_card_large_header;
      CardLargeHeaderView viewListCardLargeHeader = ViewBindings.findChildViewById(rootView, id);
      if (viewListCardLargeHeader == null) {
        break missingId;
      }

      id = R.id.view_list_card_large_header_container;
      WikiCardView viewListCardLargeHeaderContainer = ViewBindings.findChildViewById(rootView, id);
      if (viewListCardLargeHeaderContainer == null) {
        break missingId;
      }

      id = R.id.view_list_card_list;
      RecyclerView viewListCardList = ViewBindings.findChildViewById(rootView, id);
      if (viewListCardList == null) {
        break missingId;
      }

      id = R.id.view_list_card_list_container;
      WikiCardView viewListCardListContainer = ViewBindings.findChildViewById(rootView, id);
      if (viewListCardListContainer == null) {
        break missingId;
      }

      return new ViewListCardBinding((ConstraintLayout) rootView, viewListCardFooter,
          viewListCardHeader, viewListCardLargeHeader, viewListCardLargeHeaderContainer,
          viewListCardList, viewListCardListContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
