// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewLinkPreviewOverlayBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final Button linkPreviewPrimaryButton;

  @NonNull
  public final Button linkPreviewSecondaryButton;

  @NonNull
  public final Button linkPreviewTertiaryButton;

  private ViewLinkPreviewOverlayBinding(@NonNull FrameLayout rootView,
      @NonNull Button linkPreviewPrimaryButton, @NonNull Button linkPreviewSecondaryButton,
      @NonNull Button linkPreviewTertiaryButton) {
    this.rootView = rootView;
    this.linkPreviewPrimaryButton = linkPreviewPrimaryButton;
    this.linkPreviewSecondaryButton = linkPreviewSecondaryButton;
    this.linkPreviewTertiaryButton = linkPreviewTertiaryButton;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewLinkPreviewOverlayBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewLinkPreviewOverlayBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_link_preview_overlay, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewLinkPreviewOverlayBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.link_preview_primary_button;
      Button linkPreviewPrimaryButton = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewPrimaryButton == null) {
        break missingId;
      }

      id = R.id.link_preview_secondary_button;
      Button linkPreviewSecondaryButton = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewSecondaryButton == null) {
        break missingId;
      }

      id = R.id.link_preview_tertiary_button;
      Button linkPreviewTertiaryButton = ViewBindings.findChildViewById(rootView, id);
      if (linkPreviewTertiaryButton == null) {
        break missingId;
      }

      return new ViewLinkPreviewOverlayBinding((FrameLayout) rootView, linkPreviewPrimaryButton,
          linkPreviewSecondaryButton, linkPreviewTertiaryButton);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
