// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.tabs.TabLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewLanguageScrollBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final TabLayout horizontalScrollLanguages;

  @NonNull
  public final Button moreLanguages;

  private ViewLanguageScrollBinding(@NonNull View rootView,
      @NonNull TabLayout horizontalScrollLanguages, @NonNull Button moreLanguages) {
    this.rootView = rootView;
    this.horizontalScrollLanguages = horizontalScrollLanguages;
    this.moreLanguages = moreLanguages;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewLanguageScrollBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_language_scroll, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewLanguageScrollBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.horizontal_scroll_languages;
      TabLayout horizontalScrollLanguages = ViewBindings.findChildViewById(rootView, id);
      if (horizontalScrollLanguages == null) {
        break missingId;
      }

      id = R.id.more_languages;
      Button moreLanguages = ViewBindings.findChildViewById(rootView, id);
      if (moreLanguages == null) {
        break missingId;
      }

      return new ViewLanguageScrollBinding(rootView, horizontalScrollLanguages, moreLanguages);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
