// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewPlacesFiltersFooterBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView filterByBotSelected;

  @NonNull
  public final TextView footerTitle;

  private ViewPlacesFiltersFooterBinding(@NonNull LinearLayout rootView,
      @NonNull ImageView filterByBotSelected, @NonNull TextView footerTitle) {
    this.rootView = rootView;
    this.filterByBotSelected = filterByBotSelected;
    this.footerTitle = footerTitle;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewPlacesFiltersFooterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewPlacesFiltersFooterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_places_filters_footer, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewPlacesFiltersFooterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.filterByBotSelected;
      ImageView filterByBotSelected = ViewBindings.findChildViewById(rootView, id);
      if (filterByBotSelected == null) {
        break missingId;
      }

      id = R.id.footer_title;
      TextView footerTitle = ViewBindings.findChildViewById(rootView, id);
      if (footerTitle == null) {
        break missingId;
      }

      return new ViewPlacesFiltersFooterBinding((LinearLayout) rootView, filterByBotSelected,
          footerTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
