// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.AppTextView;
import org.wikipedia.views.GoneIfEmptyTextView;

public final class ViewOnboardingPageBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final View bottomOffset;

  @NonNull
  public final ImageView imageViewCentered;

  @NonNull
  public final ViewOnboardingLanguageListBinding languageListContainer;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-land/</li>
   * </ul>
   */
  @Nullable
  public final ViewOnboardingPatrollerTasksBinding patrollerTasksButtonsContainer;

  @NonNull
  public final AppTextView primaryTextView;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-land/</li>
   * </ul>
   */
  @Nullable
  public final NestedScrollView scrollView;

  /**
   * This binding is not available in all configurations.
   * <p>
   * Present:
   * <ul>
   *   <li>layout/</li>
   * </ul>
   *
   * Absent:
   * <ul>
   *   <li>layout-land/</li>
   * </ul>
   */
  @Nullable
  public final LinearLayout scrollViewContainer;

  @NonNull
  public final AppTextView secondaryTextView;

  @NonNull
  public final GoneIfEmptyTextView tertiaryTextView;

  private ViewOnboardingPageBinding(@NonNull View rootView, @NonNull View bottomOffset,
      @NonNull ImageView imageViewCentered,
      @NonNull ViewOnboardingLanguageListBinding languageListContainer,
      @Nullable ViewOnboardingPatrollerTasksBinding patrollerTasksButtonsContainer,
      @NonNull AppTextView primaryTextView, @Nullable NestedScrollView scrollView,
      @Nullable LinearLayout scrollViewContainer, @NonNull AppTextView secondaryTextView,
      @NonNull GoneIfEmptyTextView tertiaryTextView) {
    this.rootView = rootView;
    this.bottomOffset = bottomOffset;
    this.imageViewCentered = imageViewCentered;
    this.languageListContainer = languageListContainer;
    this.patrollerTasksButtonsContainer = patrollerTasksButtonsContainer;
    this.primaryTextView = primaryTextView;
    this.scrollView = scrollView;
    this.scrollViewContainer = scrollViewContainer;
    this.secondaryTextView = secondaryTextView;
    this.tertiaryTextView = tertiaryTextView;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewOnboardingPageBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_onboarding_page, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewOnboardingPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bottomOffset;
      View bottomOffset = ViewBindings.findChildViewById(rootView, id);
      if (bottomOffset == null) {
        break missingId;
      }

      id = R.id.imageViewCentered;
      ImageView imageViewCentered = ViewBindings.findChildViewById(rootView, id);
      if (imageViewCentered == null) {
        break missingId;
      }

      id = R.id.languageListContainer;
      View languageListContainer = ViewBindings.findChildViewById(rootView, id);
      if (languageListContainer == null) {
        break missingId;
      }
      ViewOnboardingLanguageListBinding binding_languageListContainer = ViewOnboardingLanguageListBinding.bind(languageListContainer);

      id = R.id.patrollerTasksButtonsContainer;
      View patrollerTasksButtonsContainer = ViewBindings.findChildViewById(rootView, id);
      ViewOnboardingPatrollerTasksBinding binding_patrollerTasksButtonsContainer = patrollerTasksButtonsContainer != null
          ? ViewOnboardingPatrollerTasksBinding.bind(patrollerTasksButtonsContainer)
          : null;

      id = R.id.primaryTextView;
      AppTextView primaryTextView = ViewBindings.findChildViewById(rootView, id);
      if (primaryTextView == null) {
        break missingId;
      }

      id = R.id.scrollView;
      NestedScrollView scrollView = ViewBindings.findChildViewById(rootView, id);

      id = R.id.scrollViewContainer;
      LinearLayout scrollViewContainer = ViewBindings.findChildViewById(rootView, id);

      id = R.id.secondaryTextView;
      AppTextView secondaryTextView = ViewBindings.findChildViewById(rootView, id);
      if (secondaryTextView == null) {
        break missingId;
      }

      id = R.id.tertiaryTextView;
      GoneIfEmptyTextView tertiaryTextView = ViewBindings.findChildViewById(rootView, id);
      if (tertiaryTextView == null) {
        break missingId;
      }

      return new ViewOnboardingPageBinding(rootView, bottomOffset, imageViewCentered,
          binding_languageListContainer, binding_patrollerTasksButtonsContainer, primaryTextView,
          scrollView, scrollViewContainer, secondaryTextView, tertiaryTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
