// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textview.MaterialTextView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewDescriptionEditLicenseBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final TextView anonWarningText;

  @NonNull
  public final MaterialTextView licenseText;

  private ViewDescriptionEditLicenseBinding(@NonNull View rootView,
      @NonNull TextView anonWarningText, @NonNull MaterialTextView licenseText) {
    this.rootView = rootView;
    this.anonWarningText = anonWarningText;
    this.licenseText = licenseText;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewDescriptionEditLicenseBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_description_edit_license, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewDescriptionEditLicenseBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.anonWarningText;
      TextView anonWarningText = ViewBindings.findChildViewById(rootView, id);
      if (anonWarningText == null) {
        break missingId;
      }

      id = R.id.licenseText;
      MaterialTextView licenseText = ViewBindings.findChildViewById(rootView, id);
      if (licenseText == null) {
        break missingId;
      }

      return new ViewDescriptionEditLicenseBinding(rootView, anonWarningText, licenseText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
