// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewEventsLayoutBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout baseView;

  @NonNull
  public final ViewOnThisDayEventBinding otdEventLayout;

  private ViewEventsLayoutBinding(@NonNull LinearLayout rootView, @NonNull LinearLayout baseView,
      @NonNull ViewOnThisDayEventBinding otdEventLayout) {
    this.rootView = rootView;
    this.baseView = baseView;
    this.otdEventLayout = otdEventLayout;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewEventsLayoutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewEventsLayoutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_events_layout, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewEventsLayoutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      LinearLayout baseView = (LinearLayout) rootView;

      id = R.id.otdEventLayout;
      View otdEventLayout = ViewBindings.findChildViewById(rootView, id);
      if (otdEventLayout == null) {
        break missingId;
      }
      ViewOnThisDayEventBinding binding_otdEventLayout = ViewOnThisDayEventBinding.bind(otdEventLayout);

      return new ViewEventsLayoutBinding((LinearLayout) rootView, baseView, binding_otdEventLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
