// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textview.MaterialTextView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiCardView;

public final class ViewPageActionOverflowBinding implements ViewBinding {
  @NonNull
  private final WikiCardView rootView;

  @NonNull
  public final MaterialTextView customizeToolbar;

  @NonNull
  public final WikiCardView overflowCardContainer;

  @NonNull
  public final MaterialTextView overflowForward;

  @NonNull
  public final LinearLayout overflowList;

  private ViewPageActionOverflowBinding(@NonNull WikiCardView rootView,
      @NonNull MaterialTextView customizeToolbar, @NonNull WikiCardView overflowCardContainer,
      @NonNull MaterialTextView overflowForward, @NonNull LinearLayout overflowList) {
    this.rootView = rootView;
    this.customizeToolbar = customizeToolbar;
    this.overflowCardContainer = overflowCardContainer;
    this.overflowForward = overflowForward;
    this.overflowList = overflowList;
  }

  @Override
  @NonNull
  public WikiCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewPageActionOverflowBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewPageActionOverflowBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_page_action_overflow, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewPageActionOverflowBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.customize_toolbar;
      MaterialTextView customizeToolbar = ViewBindings.findChildViewById(rootView, id);
      if (customizeToolbar == null) {
        break missingId;
      }

      WikiCardView overflowCardContainer = (WikiCardView) rootView;

      id = R.id.overflow_forward;
      MaterialTextView overflowForward = ViewBindings.findChildViewById(rootView, id);
      if (overflowForward == null) {
        break missingId;
      }

      id = R.id.overflowList;
      LinearLayout overflowList = ViewBindings.findChildViewById(rootView, id);
      if (overflowList == null) {
        break missingId;
      }

      return new ViewPageActionOverflowBinding((WikiCardView) rootView, customizeToolbar,
          overflowCardContainer, overflowForward, overflowList);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
