// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewEditHistoryEmptyMessagesBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView emptySearchMessage;

  @NonNull
  public final LinearLayout searchEmptyContainer;

  @NonNull
  public final TextView searchEmptyText;

  private ViewEditHistoryEmptyMessagesBinding(@NonNull LinearLayout rootView,
      @NonNull TextView emptySearchMessage, @NonNull LinearLayout searchEmptyContainer,
      @NonNull TextView searchEmptyText) {
    this.rootView = rootView;
    this.emptySearchMessage = emptySearchMessage;
    this.searchEmptyContainer = searchEmptyContainer;
    this.searchEmptyText = searchEmptyText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewEditHistoryEmptyMessagesBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewEditHistoryEmptyMessagesBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_edit_history_empty_messages, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewEditHistoryEmptyMessagesBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.empty_search_message;
      TextView emptySearchMessage = ViewBindings.findChildViewById(rootView, id);
      if (emptySearchMessage == null) {
        break missingId;
      }

      id = R.id.search_empty_container;
      LinearLayout searchEmptyContainer = ViewBindings.findChildViewById(rootView, id);
      if (searchEmptyContainer == null) {
        break missingId;
      }

      id = R.id.search_empty_text;
      TextView searchEmptyText = ViewBindings.findChildViewById(rootView, id);
      if (searchEmptyText == null) {
        break missingId;
      }

      return new ViewEditHistoryEmptyMessagesBinding((LinearLayout) rootView, emptySearchMessage,
          searchEmptyContainer, searchEmptyText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
