// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.GraphView;

public final class ViewEditHistoryStatsBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final TextView articleTitleView;

  @NonNull
  public final TextView editCountsView;

  @NonNull
  public final GraphView statsGraphView;

  private ViewEditHistoryStatsBinding(@NonNull View rootView, @NonNull TextView articleTitleView,
      @NonNull TextView editCountsView, @NonNull GraphView statsGraphView) {
    this.rootView = rootView;
    this.articleTitleView = articleTitleView;
    this.editCountsView = editCountsView;
    this.statsGraphView = statsGraphView;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewEditHistoryStatsBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_edit_history_stats, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewEditHistoryStatsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.articleTitleView;
      TextView articleTitleView = ViewBindings.findChildViewById(rootView, id);
      if (articleTitleView == null) {
        break missingId;
      }

      id = R.id.editCountsView;
      TextView editCountsView = ViewBindings.findChildViewById(rootView, id);
      if (editCountsView == null) {
        break missingId;
      }

      id = R.id.statsGraphView;
      GraphView statsGraphView = ViewBindings.findChildViewById(rootView, id);
      if (statsGraphView == null) {
        break missingId;
      }

      return new ViewEditHistoryStatsBinding(rootView, articleTitleView, editCountsView,
          statsGraphView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
