// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.PlainPasteEditText;

public final class ViewReadingListPreviewSaveDialogBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final PlainPasteEditText readingListTitle;

  @NonNull
  public final TextInputLayout readingListTitleLayout;

  @NonNull
  public final RecyclerView recyclerView;

  private ViewReadingListPreviewSaveDialogBinding(@NonNull LinearLayout rootView,
      @NonNull PlainPasteEditText readingListTitle, @NonNull TextInputLayout readingListTitleLayout,
      @NonNull RecyclerView recyclerView) {
    this.rootView = rootView;
    this.readingListTitle = readingListTitle;
    this.readingListTitleLayout = readingListTitleLayout;
    this.recyclerView = recyclerView;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewReadingListPreviewSaveDialogBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewReadingListPreviewSaveDialogBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_reading_list_preview_save_dialog, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewReadingListPreviewSaveDialogBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.readingListTitle;
      PlainPasteEditText readingListTitle = ViewBindings.findChildViewById(rootView, id);
      if (readingListTitle == null) {
        break missingId;
      }

      id = R.id.readingListTitleLayout;
      TextInputLayout readingListTitleLayout = ViewBindings.findChildViewById(rootView, id);
      if (readingListTitleLayout == null) {
        break missingId;
      }

      id = R.id.recyclerView;
      RecyclerView recyclerView = ViewBindings.findChildViewById(rootView, id);
      if (recyclerView == null) {
        break missingId;
      }

      return new ViewReadingListPreviewSaveDialogBinding((LinearLayout) rootView, readingListTitle,
          readingListTitleLayout, recyclerView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
