// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewWikitextKeyboardButtonBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ImageView expandNotch;

  @NonNull
  public final ImageView wikitextButtonImage;

  @NonNull
  public final TextView wikitextButtonText;

  private ViewWikitextKeyboardButtonBinding(@NonNull View rootView, @NonNull ImageView expandNotch,
      @NonNull ImageView wikitextButtonImage, @NonNull TextView wikitextButtonText) {
    this.rootView = rootView;
    this.expandNotch = expandNotch;
    this.wikitextButtonImage = wikitextButtonImage;
    this.wikitextButtonText = wikitextButtonText;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewWikitextKeyboardButtonBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_wikitext_keyboard_button, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewWikitextKeyboardButtonBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.expand_notch;
      ImageView expandNotch = ViewBindings.findChildViewById(rootView, id);
      if (expandNotch == null) {
        break missingId;
      }

      id = R.id.wikitext_button_image;
      ImageView wikitextButtonImage = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonImage == null) {
        break missingId;
      }

      id = R.id.wikitext_button_text;
      TextView wikitextButtonText = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonText == null) {
        break missingId;
      }

      return new ViewWikitextKeyboardButtonBinding(rootView, expandNotch, wikitextButtonImage,
          wikitextButtonText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
