// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.FaceAndColorDetectImageView;

public final class ViewPageHeaderBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final LinearLayout callToActionContainer;

  @NonNull
  public final TextView callToActionText;

  @NonNull
  public final FaceAndColorDetectImageView viewPageHeaderImage;

  @NonNull
  public final View viewPageHeaderImageGradientBottom;

  private ViewPageHeaderBinding(@NonNull View rootView, @NonNull LinearLayout callToActionContainer,
      @NonNull TextView callToActionText, @NonNull FaceAndColorDetectImageView viewPageHeaderImage,
      @NonNull View viewPageHeaderImageGradientBottom) {
    this.rootView = rootView;
    this.callToActionContainer = callToActionContainer;
    this.callToActionText = callToActionText;
    this.viewPageHeaderImage = viewPageHeaderImage;
    this.viewPageHeaderImageGradientBottom = viewPageHeaderImageGradientBottom;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewPageHeaderBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_page_header, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewPageHeaderBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.call_to_action_container;
      LinearLayout callToActionContainer = ViewBindings.findChildViewById(rootView, id);
      if (callToActionContainer == null) {
        break missingId;
      }

      id = R.id.call_to_action_text;
      TextView callToActionText = ViewBindings.findChildViewById(rootView, id);
      if (callToActionText == null) {
        break missingId;
      }

      id = R.id.view_page_header_image;
      FaceAndColorDetectImageView viewPageHeaderImage = ViewBindings.findChildViewById(rootView, id);
      if (viewPageHeaderImage == null) {
        break missingId;
      }

      id = R.id.view_page_header_image_gradient_bottom;
      View viewPageHeaderImageGradientBottom = ViewBindings.findChildViewById(rootView, id);
      if (viewPageHeaderImageGradientBottom == null) {
        break missingId;
      }

      return new ViewPageHeaderBinding(rootView, callToActionContainer, callToActionText,
          viewPageHeaderImage, viewPageHeaderImageGradientBottom);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
