// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikitextKeyboardButtonView;

public final class ViewWikitextKeyboardFormattingBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final ImageView closeButton;

  @NonNull
  public final HorizontalScrollView wikiTextKeyboardFormattingHorizontalScrollView;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonBold;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonCode;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonItalic;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonStrikethrough;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonSub;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonSup;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonTextLarge;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonTextSmall;

  @NonNull
  public final WikitextKeyboardButtonView wikitextButtonUnderline;

  private ViewWikitextKeyboardFormattingBinding(@NonNull View rootView,
      @NonNull ImageView closeButton,
      @NonNull HorizontalScrollView wikiTextKeyboardFormattingHorizontalScrollView,
      @NonNull WikitextKeyboardButtonView wikitextButtonBold,
      @NonNull WikitextKeyboardButtonView wikitextButtonCode,
      @NonNull WikitextKeyboardButtonView wikitextButtonItalic,
      @NonNull WikitextKeyboardButtonView wikitextButtonStrikethrough,
      @NonNull WikitextKeyboardButtonView wikitextButtonSub,
      @NonNull WikitextKeyboardButtonView wikitextButtonSup,
      @NonNull WikitextKeyboardButtonView wikitextButtonTextLarge,
      @NonNull WikitextKeyboardButtonView wikitextButtonTextSmall,
      @NonNull WikitextKeyboardButtonView wikitextButtonUnderline) {
    this.rootView = rootView;
    this.closeButton = closeButton;
    this.wikiTextKeyboardFormattingHorizontalScrollView = wikiTextKeyboardFormattingHorizontalScrollView;
    this.wikitextButtonBold = wikitextButtonBold;
    this.wikitextButtonCode = wikitextButtonCode;
    this.wikitextButtonItalic = wikitextButtonItalic;
    this.wikitextButtonStrikethrough = wikitextButtonStrikethrough;
    this.wikitextButtonSub = wikitextButtonSub;
    this.wikitextButtonSup = wikitextButtonSup;
    this.wikitextButtonTextLarge = wikitextButtonTextLarge;
    this.wikitextButtonTextSmall = wikitextButtonTextSmall;
    this.wikitextButtonUnderline = wikitextButtonUnderline;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewWikitextKeyboardFormattingBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_wikitext_keyboard_formatting, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewWikitextKeyboardFormattingBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.close_button;
      ImageView closeButton = ViewBindings.findChildViewById(rootView, id);
      if (closeButton == null) {
        break missingId;
      }

      id = R.id.wiki_text_keyboard_formatting_horizontal_scroll_view;
      HorizontalScrollView wikiTextKeyboardFormattingHorizontalScrollView = ViewBindings.findChildViewById(rootView, id);
      if (wikiTextKeyboardFormattingHorizontalScrollView == null) {
        break missingId;
      }

      id = R.id.wikitext_button_bold;
      WikitextKeyboardButtonView wikitextButtonBold = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonBold == null) {
        break missingId;
      }

      id = R.id.wikitext_button_code;
      WikitextKeyboardButtonView wikitextButtonCode = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonCode == null) {
        break missingId;
      }

      id = R.id.wikitext_button_italic;
      WikitextKeyboardButtonView wikitextButtonItalic = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonItalic == null) {
        break missingId;
      }

      id = R.id.wikitext_button_strikethrough;
      WikitextKeyboardButtonView wikitextButtonStrikethrough = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonStrikethrough == null) {
        break missingId;
      }

      id = R.id.wikitext_button_sub;
      WikitextKeyboardButtonView wikitextButtonSub = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonSub == null) {
        break missingId;
      }

      id = R.id.wikitext_button_sup;
      WikitextKeyboardButtonView wikitextButtonSup = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonSup == null) {
        break missingId;
      }

      id = R.id.wikitext_button_text_large;
      WikitextKeyboardButtonView wikitextButtonTextLarge = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonTextLarge == null) {
        break missingId;
      }

      id = R.id.wikitext_button_text_small;
      WikitextKeyboardButtonView wikitextButtonTextSmall = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonTextSmall == null) {
        break missingId;
      }

      id = R.id.wikitext_button_underline;
      WikitextKeyboardButtonView wikitextButtonUnderline = ViewBindings.findChildViewById(rootView, id);
      if (wikitextButtonUnderline == null) {
        break missingId;
      }

      return new ViewWikitextKeyboardFormattingBinding(rootView, closeButton,
          wikiTextKeyboardFormattingHorizontalScrollView, wikitextButtonBold, wikitextButtonCode,
          wikitextButtonItalic, wikitextButtonStrikethrough, wikitextButtonSub, wikitextButtonSup,
          wikitextButtonTextLarge, wikitextButtonTextSmall, wikitextButtonUnderline);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
