// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.Space;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class ViewCardOfflineBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button viewCardOfflineButtonRetry;

  @NonNull
  public final Space viewCardOfflineTopPadding;

  private ViewCardOfflineBinding(@NonNull LinearLayout rootView,
      @NonNull Button viewCardOfflineButtonRetry, @NonNull Space viewCardOfflineTopPadding) {
    this.rootView = rootView;
    this.viewCardOfflineButtonRetry = viewCardOfflineButtonRetry;
    this.viewCardOfflineTopPadding = viewCardOfflineTopPadding;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewCardOfflineBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewCardOfflineBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_card_offline, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewCardOfflineBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.view_card_offline_button_retry;
      Button viewCardOfflineButtonRetry = ViewBindings.findChildViewById(rootView, id);
      if (viewCardOfflineButtonRetry == null) {
        break missingId;
      }

      id = R.id.view_card_offline_top_padding;
      Space viewCardOfflineTopPadding = ViewBindings.findChildViewById(rootView, id);
      if (viewCardOfflineTopPadding == null) {
        break missingId;
      }

      return new ViewCardOfflineBinding((LinearLayout) rootView, viewCardOfflineButtonRetry,
          viewCardOfflineTopPadding);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
