// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.FaceAndColorDetectImageView;
import org.wikipedia.views.GoneIfEmptyTextView;

public final class ViewWikiArticleCardBinding implements ViewBinding {
  @NonNull
  private final View rootView;

  @NonNull
  public final GoneIfEmptyTextView articleDescription;

  @NonNull
  public final View articleDivider;

  @NonNull
  public final TextView articleExtract;

  @NonNull
  public final FaceAndColorDetectImageView articleImage;

  @NonNull
  public final FrameLayout articleImageContainer;

  @NonNull
  public final TextView articleTitle;

  private ViewWikiArticleCardBinding(@NonNull View rootView,
      @NonNull GoneIfEmptyTextView articleDescription, @NonNull View articleDivider,
      @NonNull TextView articleExtract, @NonNull FaceAndColorDetectImageView articleImage,
      @NonNull FrameLayout articleImageContainer, @NonNull TextView articleTitle) {
    this.rootView = rootView;
    this.articleDescription = articleDescription;
    this.articleDivider = articleDivider;
    this.articleExtract = articleExtract;
    this.articleImage = articleImage;
    this.articleImageContainer = articleImageContainer;
    this.articleTitle = articleTitle;
  }

  @Override
  @NonNull
  public View getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewWikiArticleCardBinding inflate(@NonNull LayoutInflater inflater,
      @NonNull ViewGroup parent) {
    if (parent == null) {
      throw new NullPointerException("parent");
    }
    inflater.inflate(R.layout.view_wiki_article_card, parent);
    return bind(parent);
  }

  @NonNull
  public static ViewWikiArticleCardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.articleDescription;
      GoneIfEmptyTextView articleDescription = ViewBindings.findChildViewById(rootView, id);
      if (articleDescription == null) {
        break missingId;
      }

      id = R.id.articleDivider;
      View articleDivider = ViewBindings.findChildViewById(rootView, id);
      if (articleDivider == null) {
        break missingId;
      }

      id = R.id.articleExtract;
      TextView articleExtract = ViewBindings.findChildViewById(rootView, id);
      if (articleExtract == null) {
        break missingId;
      }

      id = R.id.articleImage;
      FaceAndColorDetectImageView articleImage = ViewBindings.findChildViewById(rootView, id);
      if (articleImage == null) {
        break missingId;
      }

      id = R.id.articleImageContainer;
      FrameLayout articleImageContainer = ViewBindings.findChildViewById(rootView, id);
      if (articleImageContainer == null) {
        break missingId;
      }

      id = R.id.articleTitle;
      TextView articleTitle = ViewBindings.findChildViewById(rootView, id);
      if (articleTitle == null) {
        break missingId;
      }

      return new ViewWikiArticleCardBinding(rootView, articleDescription, articleDivider,
          articleExtract, articleImage, articleImageContainer, articleTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
