// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.LangCodeView;

public final class ViewPlacesFilterItemBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LangCodeView placesFilterLangCode;

  @NonNull
  public final ImageView placesFilterRadio;

  @NonNull
  public final TextView placesFilterTitle;

  private ViewPlacesFilterItemBinding(@NonNull LinearLayout rootView,
      @NonNull LangCodeView placesFilterLangCode, @NonNull ImageView placesFilterRadio,
      @NonNull TextView placesFilterTitle) {
    this.rootView = rootView;
    this.placesFilterLangCode = placesFilterLangCode;
    this.placesFilterRadio = placesFilterRadio;
    this.placesFilterTitle = placesFilterTitle;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewPlacesFilterItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewPlacesFilterItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_places_filter_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewPlacesFilterItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.placesFilterLangCode;
      LangCodeView placesFilterLangCode = ViewBindings.findChildViewById(rootView, id);
      if (placesFilterLangCode == null) {
        break missingId;
      }

      id = R.id.placesFilterRadio;
      ImageView placesFilterRadio = ViewBindings.findChildViewById(rootView, id);
      if (placesFilterRadio == null) {
        break missingId;
      }

      id = R.id.placesFilterTitle;
      TextView placesFilterTitle = ViewBindings.findChildViewById(rootView, id);
      if (placesFilterTitle == null) {
        break missingId;
      }

      return new ViewPlacesFilterItemBinding((LinearLayout) rootView, placesFilterLangCode,
          placesFilterRadio, placesFilterTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
