// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.feed.view.CardFooterView;
import org.wikipedia.feed.view.CardHeaderView;

public final class ViewCardOnThisDayBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final CardFooterView cardFooterView;

  @NonNull
  public final CardHeaderView cardHeader;

  @NonNull
  public final ViewOnThisDayEventBinding eventLayout;

  @NonNull
  public final FrameLayout onThisDayCardViewClickContainer;

  @NonNull
  public final ConstraintLayout rtlContainer;

  @NonNull
  public final LinearLayout textContainer;

  private ViewCardOnThisDayBinding(@NonNull LinearLayout rootView,
      @NonNull CardFooterView cardFooterView, @NonNull CardHeaderView cardHeader,
      @NonNull ViewOnThisDayEventBinding eventLayout,
      @NonNull FrameLayout onThisDayCardViewClickContainer, @NonNull ConstraintLayout rtlContainer,
      @NonNull LinearLayout textContainer) {
    this.rootView = rootView;
    this.cardFooterView = cardFooterView;
    this.cardHeader = cardHeader;
    this.eventLayout = eventLayout;
    this.onThisDayCardViewClickContainer = onThisDayCardViewClickContainer;
    this.rtlContainer = rtlContainer;
    this.textContainer = textContainer;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewCardOnThisDayBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewCardOnThisDayBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_card_on_this_day, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewCardOnThisDayBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.card_footer_view;
      CardFooterView cardFooterView = ViewBindings.findChildViewById(rootView, id);
      if (cardFooterView == null) {
        break missingId;
      }

      id = R.id.card_header;
      CardHeaderView cardHeader = ViewBindings.findChildViewById(rootView, id);
      if (cardHeader == null) {
        break missingId;
      }

      id = R.id.event_layout;
      View eventLayout = ViewBindings.findChildViewById(rootView, id);
      if (eventLayout == null) {
        break missingId;
      }
      ViewOnThisDayEventBinding binding_eventLayout = ViewOnThisDayEventBinding.bind(eventLayout);

      id = R.id.on_this_day_card_view_click_container;
      FrameLayout onThisDayCardViewClickContainer = ViewBindings.findChildViewById(rootView, id);
      if (onThisDayCardViewClickContainer == null) {
        break missingId;
      }

      id = R.id.rtl_container;
      ConstraintLayout rtlContainer = ViewBindings.findChildViewById(rootView, id);
      if (rtlContainer == null) {
        break missingId;
      }

      id = R.id.text_container;
      LinearLayout textContainer = ViewBindings.findChildViewById(rootView, id);
      if (textContainer == null) {
        break missingId;
      }

      return new ViewCardOnThisDayBinding((LinearLayout) rootView, cardFooterView, cardHeader,
          binding_eventLayout, onThisDayCardViewClickContainer, rtlContainer, textContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
