// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;
import org.wikipedia.views.WikiCardView;

public final class ViewNotificationSearchBarBinding implements ViewBinding {
  @NonNull
  private final WikiCardView rootView;

  @NonNull
  public final TextView filterCount;

  @NonNull
  public final ImageView notificationFilterButton;

  @NonNull
  public final WikiCardView searchContainer;

  private ViewNotificationSearchBarBinding(@NonNull WikiCardView rootView,
      @NonNull TextView filterCount, @NonNull ImageView notificationFilterButton,
      @NonNull WikiCardView searchContainer) {
    this.rootView = rootView;
    this.filterCount = filterCount;
    this.notificationFilterButton = notificationFilterButton;
    this.searchContainer = searchContainer;
  }

  @Override
  @NonNull
  public WikiCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ViewNotificationSearchBarBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ViewNotificationSearchBarBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.view_notification_search_bar, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ViewNotificationSearchBarBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.filter_count;
      TextView filterCount = ViewBindings.findChildViewById(rootView, id);
      if (filterCount == null) {
        break missingId;
      }

      id = R.id.notification_filter_button;
      ImageView notificationFilterButton = ViewBindings.findChildViewById(rootView, id);
      if (notificationFilterButton == null) {
        break missingId;
      }

      WikiCardView searchContainer = (WikiCardView) rootView;

      return new ViewNotificationSearchBarBinding((WikiCardView) rootView, filterCount,
          notificationFilterButton, searchContainer);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
