// Generated by view binder compiler. Do not edit!
package org.wikipedia.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.wikipedia.R;

public final class WidgetFeaturedPageBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout widgetContainer;

  @NonNull
  public final TextView widgetContentDescription;

  @NonNull
  public final ImageView widgetContentThumbnail;

  @NonNull
  public final TextView widgetContentTitle;

  private WidgetFeaturedPageBinding(@NonNull LinearLayout rootView,
      @NonNull LinearLayout widgetContainer, @NonNull TextView widgetContentDescription,
      @NonNull ImageView widgetContentThumbnail, @NonNull TextView widgetContentTitle) {
    this.rootView = rootView;
    this.widgetContainer = widgetContainer;
    this.widgetContentDescription = widgetContentDescription;
    this.widgetContentThumbnail = widgetContentThumbnail;
    this.widgetContentTitle = widgetContentTitle;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static WidgetFeaturedPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static WidgetFeaturedPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.widget_featured_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static WidgetFeaturedPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      LinearLayout widgetContainer = (LinearLayout) rootView;

      id = R.id.widget_content_description;
      TextView widgetContentDescription = ViewBindings.findChildViewById(rootView, id);
      if (widgetContentDescription == null) {
        break missingId;
      }

      id = R.id.widget_content_thumbnail;
      ImageView widgetContentThumbnail = ViewBindings.findChildViewById(rootView, id);
      if (widgetContentThumbnail == null) {
        break missingId;
      }

      id = R.id.widget_content_title;
      TextView widgetContentTitle = ViewBindings.findChildViewById(rootView, id);
      if (widgetContentTitle == null) {
        break missingId;
      }

      return new WidgetFeaturedPageBinding((LinearLayout) rootView, widgetContainer,
          widgetContentDescription, widgetContentThumbnail, widgetContentTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
